.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.set fp=64

.section .text, "ax"

/* Generated by spimdisasm 1.32.1 */

glabel func_global_asm_80612790
    /* 2017490 80612790 24840400 */  addiu      $a0, $a0, 0x400
  glabel func_global_asm_80612794
    /* 2017494 80612794 24090400 */  addiu      $t1, $zero, 0x400
    /* 2017498 80612798 00895024 */  and        $t2, $a0, $t1
    /* 201749C 8061279C 11400002 */  beqz       $t2, .Lglobal_asm_806127A8
    /* 20174A0 806127A0 308803FF */   andi      $t0, $a0, 0x3FF
    /* 20174A4 806127A4 01284023 */  subu       $t0, $t1, $t0
  .Lglobal_asm_806127A8:
    /* 20174A8 806127A8 00084842 */  srl        $t1, $t0, 1
    /* 20174AC 806127AC 3C0A8062 */  lui        $t2, %hi(D_global_asm_8061ACA0)
    /* 20174B0 806127B0 00094880 */  sll        $t1, $t1, 2
    /* 20174B4 806127B4 254AACA0 */  addiu      $t2, $t2, %lo(D_global_asm_8061ACA0)
    /* 20174B8 806127B8 012A4821 */  addu       $t1, $t1, $t2
    /* 20174BC 806127BC 308A0001 */  andi       $t2, $a0, 0x1
    /* 20174C0 806127C0 11400007 */  beqz       $t2, .Lglobal_asm_806127E0
    /* 20174C4 806127C4 C5200000 */   lwc1      $f0, 0x0($t1)
    /* 20174C8 806127C8 C5240004 */  lwc1       $f4, 0x4($t1)
    /* 20174CC 806127CC 3C013F00 */  lui        $at, (0x3F000000 >> 16)
    /* 20174D0 806127D0 44813000 */  mtc1       $at, $f6
    /* 20174D4 806127D4 46040000 */  add.s      $f0, $f0, $f4
    /* 20174D8 806127D8 46060002 */  mul.s      $f0, $f0, $f6
    /* 20174DC 806127DC 00000000 */  nop
  .Lglobal_asm_806127E0:
    /* 20174E0 806127E0 308A0800 */  andi       $t2, $a0, 0x800
    /* 20174E4 806127E4 11400004 */  beqz       $t2, .Lglobal_asm_806127F8
    /* 20174E8 806127E8 00000000 */   nop
    /* 20174EC 806127EC 44802000 */  mtc1       $zero, $f4
    /* 20174F0 806127F0 00000000 */  nop
    /* 20174F4 806127F4 46002001 */  sub.s      $f0, $f4, $f0
  .Lglobal_asm_806127F8:
    /* 20174F8 806127F8 03E00008 */  jr         $ra
    /* 20174FC 806127FC 00000000 */   nop
.size func_global_asm_80612790, . - func_global_asm_80612790

glabel func_global_asm_80612800
    /* 2017500 80612800 27BDFFF8 */  addiu      $sp, $sp, -0x8
    /* 2017504 80612804 AFBF0000 */  sw         $ra, 0x0($sp)
    /* 2017508 80612808 AFBF0004 */  sw         $ra, 0x4($sp)
    /* 201750C 8061280C 0C1849E5 */  jal        func_global_asm_80612794
    /* 2017510 80612810 00000000 */   nop
    /* 2017514 80612814 0C1849E4 */  jal        func_global_asm_80612790
    /* 2017518 80612818 46000306 */   mov.s     $f12, $f0
    /* 201751C 8061281C 8FBF0000 */  lw         $ra, 0x0($sp)
    /* 2017520 80612820 8FBF0004 */  lw         $ra, 0x4($sp)
    /* 2017524 80612824 46006003 */  div.s      $f0, $f12, $f0
    /* 2017528 80612828 27BD0008 */  addiu      $sp, $sp, 0x8
    /* 201752C 8061282C 03E00008 */  jr         $ra
    /* 2017530 80612830 00000000 */   nop
    /* 2017534 80612834 00000000 */  nop
    /* 2017538 80612838 00000000 */  nop
    /* 201753C 8061283C 00000000 */  nop
.size func_global_asm_80612800, . - func_global_asm_80612800
