.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.set fp=64

.section .text, "ax"

/* Generated by spimdisasm 1.32.1 */

glabel func_global_asm_80612D10
    /* 2017A10 80612D10 3C018075 */  lui        $at, %hi(D_global_asm_80757320)
    /* 2017A14 80612D14 C42A7320 */  lwc1       $f10, %lo(D_global_asm_80757320)($at)
    /* 2017A18 80612D18 460A6300 */  add.s      $f12, $f12, $f10
.size func_global_asm_80612D10, . - func_global_asm_80612D10

glabel func_global_asm_80612D1C
    /* 2017A1C 80612D1C 44086000 */  mfc1       $t0, $f12
    /* 2017A20 80612D20 00084583 */  sra        $t0, $t0, 22
    /* 2017A24 80612D24 310801FF */  andi       $t0, $t0, 0x1FF
    /* 2017A28 80612D28 290100FF */  slti       $at, $t0, 0xFF
    /* 2017A2C 80612D2C 10200018 */  beqz       $at, .Lglobal_asm_80612D90
    /* 2017A30 80612D30 00000000 */   nop
    /* 2017A34 80612D34 290100E6 */  slti       $at, $t0, 0xE6
    /* 2017A38 80612D38 1420003C */  bnez       $at, func_global_asm_80612E2C
    /* 2017A3C 80612D3C 46006006 */   mov.s     $f0, $f12
    /* 2017A40 80612D40 460C6402 */  mul.s      $f16, $f12, $f12
    /* 2017A44 80612D44 3C018075 */  lui        $at, %hi(D_global_asm_80757324)
    /* 2017A48 80612D48 C4327324 */  lwc1       $f18, %lo(D_global_asm_80757324)($at)
    /* 2017A4C 80612D4C 46109482 */  mul.s      $f18, $f18, $f16
    /* 2017A50 80612D50 3C018075 */  lui        $at, %hi(D_global_asm_80757328)
    /* 2017A54 80612D54 C42A7328 */  lwc1       $f10, %lo(D_global_asm_80757328)($at)
    /* 2017A58 80612D58 46125480 */  add.s      $f18, $f10, $f18
    /* 2017A5C 80612D5C 46109482 */  mul.s      $f18, $f18, $f16
    /* 2017A60 80612D60 3C018075 */  lui        $at, %hi(D_global_asm_8075732C)
    /* 2017A64 80612D64 C42A732C */  lwc1       $f10, %lo(D_global_asm_8075732C)($at)
    /* 2017A68 80612D68 46125480 */  add.s      $f18, $f10, $f18
    /* 2017A6C 80612D6C 46109482 */  mul.s      $f18, $f18, $f16
    /* 2017A70 80612D70 3C018075 */  lui        $at, %hi(D_global_asm_80757330)
    /* 2017A74 80612D74 C42A7330 */  lwc1       $f10, %lo(D_global_asm_80757330)($at)
    /* 2017A78 80612D78 46125480 */  add.s      $f18, $f10, $f18
    /* 2017A7C 80612D7C 460C8282 */  mul.s      $f10, $f16, $f12
    /* 2017A80 80612D80 00000000 */  nop
    /* 2017A84 80612D84 460A9482 */  mul.s      $f18, $f18, $f10
    /* 2017A88 80612D88 08184B8B */  j          func_global_asm_80612E2C
    /* 2017A8C 80612D8C 460C9000 */   add.s     $f0, $f18, $f12
  .Lglobal_asm_80612D90:
    /* 2017A90 80612D90 29010136 */  slti       $at, $t0, 0x136
    /* 2017A94 80612D94 50200025 */  beql       $at, $zero, func_global_asm_80612E2C
    /* 2017A98 80612D98 44800000 */   mtc1      $zero, $f0
    /* 2017A9C 80612D9C 3C018075 */  lui        $at, %hi(D_global_asm_80757334)
    /* 2017AA0 80612DA0 C4307334 */  lwc1       $f16, %lo(D_global_asm_80757334)($at)
    /* 2017AA4 80612DA4 460C8402 */  mul.s      $f16, $f16, $f12
    /* 2017AA8 80612DA8 46008424 */  cvt.w.s    $f16, $f16
    /* 2017AAC 80612DAC 44098000 */  mfc1       $t1, $f16
    /* 2017AB0 80612DB0 46808420 */  cvt.s.w    $f16, $f16
    /* 2017AB4 80612DB4 3C018075 */  lui        $at, %hi(D_global_asm_80757338)
    /* 2017AB8 80612DB8 C4327338 */  lwc1       $f18, %lo(D_global_asm_80757338)($at)
    /* 2017ABC 80612DBC 46109482 */  mul.s      $f18, $f18, $f16
    /* 2017AC0 80612DC0 46126301 */  sub.s      $f12, $f12, $f18
    /* 2017AC4 80612DC4 3C018075 */  lui        $at, %hi(D_global_asm_8075733C)
    /* 2017AC8 80612DC8 C432733C */  lwc1       $f18, %lo(D_global_asm_8075733C)($at)
    /* 2017ACC 80612DCC 46109482 */  mul.s      $f18, $f18, $f16
    /* 2017AD0 80612DD0 46126301 */  sub.s      $f12, $f12, $f18
    /* 2017AD4 80612DD4 460C6402 */  mul.s      $f16, $f12, $f12
    /* 2017AD8 80612DD8 3C018075 */  lui        $at, %hi(D_global_asm_80757340)
    /* 2017ADC 80612DDC C4327340 */  lwc1       $f18, %lo(D_global_asm_80757340)($at)
    /* 2017AE0 80612DE0 46109482 */  mul.s      $f18, $f18, $f16
    /* 2017AE4 80612DE4 3C018075 */  lui        $at, %hi(D_global_asm_80757344)
    /* 2017AE8 80612DE8 C42A7344 */  lwc1       $f10, %lo(D_global_asm_80757344)($at)
    /* 2017AEC 80612DEC 46125480 */  add.s      $f18, $f10, $f18
    /* 2017AF0 80612DF0 46109482 */  mul.s      $f18, $f18, $f16
    /* 2017AF4 80612DF4 3C018075 */  lui        $at, %hi(D_global_asm_80757348)
    /* 2017AF8 80612DF8 C42A7348 */  lwc1       $f10, %lo(D_global_asm_80757348)($at)
    /* 2017AFC 80612DFC 46125480 */  add.s      $f18, $f10, $f18
    /* 2017B00 80612E00 46109482 */  mul.s      $f18, $f18, $f16
    /* 2017B04 80612E04 3C018075 */  lui        $at, %hi(D_global_asm_8075734C)
    /* 2017B08 80612E08 C42A734C */  lwc1       $f10, %lo(D_global_asm_8075734C)($at)
    /* 2017B0C 80612E0C 46125480 */  add.s      $f18, $f10, $f18
    /* 2017B10 80612E10 46109482 */  mul.s      $f18, $f18, $f16
    /* 2017B14 80612E14 00000000 */  nop
    /* 2017B18 80612E18 460C9482 */  mul.s      $f18, $f18, $f12
    /* 2017B1C 80612E1C 460C9000 */  add.s      $f0, $f18, $f12
    /* 2017B20 80612E20 31290001 */  andi       $t1, $t1, 0x1
    /* 2017B24 80612E24 55200001 */  bnel       $t1, $zero, func_global_asm_80612E2C
    /* 2017B28 80612E28 46000007 */   neg.s     $f0, $f0
  glabel func_global_asm_80612E2C
    /* 2017B2C 80612E2C 03E00008 */  jr         $ra
    /* 2017B30 80612E30 00000000 */   nop
    /* 2017B34 80612E34 00000000 */  nop
    /* 2017B38 80612E38 00000000 */  nop
    /* 2017B3C 80612E3C 00000000 */  nop
.size func_global_asm_80612D1C, . - func_global_asm_80612D1C
