.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.set fp=64

.section .text, "ax"

/* Generated by spimdisasm 1.32.1 */

/* Handwritten function */
glabel func_global_asm_80610310
    /* 2015010 80610310 27BDFFF8 */  addiu      $sp, $sp, -0x8
    /* 2015014 80610314 FFBF0000 */  sd         $ra, 0x0($sp)
    /* 2015018 80610318 40026000 */  mfc0       $v0, $12 /* handwritten instruction */
    /* 201501C 8061031C DFBF0000 */  ld         $ra, 0x0($sp)
    /* 2015020 80610320 27BD0008 */  addiu      $sp, $sp, 0x8
    /* 2015024 80610324 03E00008 */  jr         $ra
    /* 2015028 80610328 00000000 */   nop
.size func_global_asm_80610310, . - func_global_asm_80610310

/* Handwritten function */
glabel func_global_asm_8061032C
    /* 201502C 8061032C 40086000 */  mfc0       $t0, $12 /* handwritten instruction */
    /* 2015030 80610330 2401FFFE */  addiu      $at, $zero, -0x2
    /* 2015034 80610334 01014824 */  and        $t1, $t0, $at
    /* 2015038 80610338 40896000 */  mtc0       $t1, $12 /* handwritten instruction */
    /* 201503C 8061033C 31020001 */  andi       $v0, $t0, 0x1
    /* 2015040 80610340 00000000 */  nop
    /* 2015044 80610344 03E00008 */  jr         $ra
    /* 2015048 80610348 00000000 */   nop
    /* 201504C 8061034C 00000000 */  nop
.size func_global_asm_8061032C, . - func_global_asm_8061032C
