.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.set fp=64

.section .text, "ax"

/* Generated by spimdisasm 1.32.1 */

/* Handwritten function */
glabel __osExceptionPreamble
    /* 9CA0 800090A0 3C1A8001 */  lui        $k0, %hi(__osException) /* handwritten instruction */
    /* 9CA4 800090A4 275A90B0 */  addiu      $k0, $k0, %lo(__osException) /* handwritten instruction */
    /* 9CA8 800090A8 03400008 */  jr         $k0
    /* 9CAC 800090AC 00000000 */   nop
.size __osExceptionPreamble, . - __osExceptionPreamble

/* Handwritten function */
glabel __osException
    /* 9CB0 800090B0 3C1A8001 */  lui        $k0, %hi(__osThreadSave) /* handwritten instruction */
    /* 9CB4 800090B4 275A6340 */  addiu      $k0, $k0, %lo(__osThreadSave) /* handwritten instruction */
    /* 9CB8 800090B8 FF410020 */  sd         $at, 0x20($k0) /* handwritten instruction */
    /* 9CBC 800090BC 401B6000 */  mfc0       $k1, $12 /* handwritten instruction */
    /* 9CC0 800090C0 AF5B0118 */  sw         $k1, 0x118($k0) /* handwritten instruction */
    /* 9CC4 800090C4 2401FFFC */  addiu      $at, $zero, -0x4
    /* 9CC8 800090C8 0361D824 */  and        $k1, $k1, $at
    /* 9CCC 800090CC 409B6000 */  mtc0       $k1, $12 /* handwritten instruction */
    /* 9CD0 800090D0 FF480058 */  sd         $t0, 0x58($k0) /* handwritten instruction */
    /* 9CD4 800090D4 FF490060 */  sd         $t1, 0x60($k0) /* handwritten instruction */
    /* 9CD8 800090D8 FF4A0068 */  sd         $t2, 0x68($k0) /* handwritten instruction */
    /* 9CDC 800090DC AF400018 */  sw         $zero, 0x18($k0) /* handwritten instruction */
    /* 9CE0 800090E0 40086800 */  mfc0       $t0, $13 /* handwritten instruction */
    /* 9CE4 800090E4 03404025 */  or         $t0, $k0, $zero
    /* 9CE8 800090E8 3C1A8001 */  lui        $k0, %hi(__osRunningThread) /* handwritten instruction */
    /* 9CEC 800090EC 8F5A00F0 */  lw         $k0, %lo(__osRunningThread)($k0) /* handwritten instruction */
    /* 9CF0 800090F0 DD090020 */  ld         $t1, 0x20($t0)
    /* 9CF4 800090F4 FF490020 */  sd         $t1, 0x20($k0) /* handwritten instruction */
    /* 9CF8 800090F8 DD090118 */  ld         $t1, 0x118($t0)
    /* 9CFC 800090FC FF490118 */  sd         $t1, 0x118($k0) /* handwritten instruction */
    /* 9D00 80009100 DD090058 */  ld         $t1, 0x58($t0)
    /* 9D04 80009104 FF490058 */  sd         $t1, 0x58($k0) /* handwritten instruction */
    /* 9D08 80009108 DD090060 */  ld         $t1, 0x60($t0)
    /* 9D0C 8000910C FF490060 */  sd         $t1, 0x60($k0) /* handwritten instruction */
    /* 9D10 80009110 DD090068 */  ld         $t1, 0x68($t0)
    /* 9D14 80009114 FF490068 */  sd         $t1, 0x68($k0) /* handwritten instruction */
    /* 9D18 80009118 8F5B0118 */  lw         $k1, 0x118($k0) /* handwritten instruction */
    /* 9D1C 8000911C 00004012 */  mflo       $t0
    /* 9D20 80009120 FF480108 */  sd         $t0, 0x108($k0) /* handwritten instruction */
    /* 9D24 80009124 00004010 */  mfhi       $t0
    /* 9D28 80009128 3369FF00 */  andi       $t1, $k1, 0xFF00 /* handwritten instruction */
    /* 9D2C 8000912C FF420028 */  sd         $v0, 0x28($k0) /* handwritten instruction */
    /* 9D30 80009130 FF430030 */  sd         $v1, 0x30($k0) /* handwritten instruction */
    /* 9D34 80009134 FF440038 */  sd         $a0, 0x38($k0) /* handwritten instruction */
    /* 9D38 80009138 FF450040 */  sd         $a1, 0x40($k0) /* handwritten instruction */
    /* 9D3C 8000913C FF460048 */  sd         $a2, 0x48($k0) /* handwritten instruction */
    /* 9D40 80009140 FF470050 */  sd         $a3, 0x50($k0) /* handwritten instruction */
    /* 9D44 80009144 FF4B0070 */  sd         $t3, 0x70($k0) /* handwritten instruction */
    /* 9D48 80009148 FF4C0078 */  sd         $t4, 0x78($k0) /* handwritten instruction */
    /* 9D4C 8000914C FF4D0080 */  sd         $t5, 0x80($k0) /* handwritten instruction */
    /* 9D50 80009150 FF4E0088 */  sd         $t6, 0x88($k0) /* handwritten instruction */
    /* 9D54 80009154 FF4F0090 */  sd         $t7, 0x90($k0) /* handwritten instruction */
    /* 9D58 80009158 FF500098 */  sd         $s0, 0x98($k0) /* handwritten instruction */
    /* 9D5C 8000915C FF5100A0 */  sd         $s1, 0xA0($k0) /* handwritten instruction */
    /* 9D60 80009160 FF5200A8 */  sd         $s2, 0xA8($k0) /* handwritten instruction */
    /* 9D64 80009164 FF5300B0 */  sd         $s3, 0xB0($k0) /* handwritten instruction */
    /* 9D68 80009168 FF5400B8 */  sd         $s4, 0xB8($k0) /* handwritten instruction */
    /* 9D6C 8000916C FF5500C0 */  sd         $s5, 0xC0($k0) /* handwritten instruction */
    /* 9D70 80009170 FF5600C8 */  sd         $s6, 0xC8($k0) /* handwritten instruction */
    /* 9D74 80009174 FF5700D0 */  sd         $s7, 0xD0($k0) /* handwritten instruction */
    /* 9D78 80009178 FF5800D8 */  sd         $t8, 0xD8($k0) /* handwritten instruction */
    /* 9D7C 8000917C FF5900E0 */  sd         $t9, 0xE0($k0) /* handwritten instruction */
    /* 9D80 80009180 FF5C00E8 */  sd         $gp, 0xE8($k0) /* handwritten instruction */
    /* 9D84 80009184 FF5D00F0 */  sd         $sp, 0xF0($k0) /* handwritten instruction */
    /* 9D88 80009188 FF5E00F8 */  sd         $fp, 0xF8($k0) /* handwritten instruction */
    /* 9D8C 8000918C FF5F0100 */  sd         $ra, 0x100($k0) /* handwritten instruction */
    /* 9D90 80009190 11200011 */  beqz       $t1, .Ldk64_boot_800091D8
    /* 9D94 80009194 FF480110 */   sd        $t0, 0x110($k0) /* handwritten instruction */
    /* 9D98 80009198 3C088001 */  lui        $t0, %hi(__OSGlobalIntMask)
    /* 9D9C 8000919C 250800B0 */  addiu      $t0, $t0, %lo(__OSGlobalIntMask)
    /* 9DA0 800091A0 8D080000 */  lw         $t0, 0x0($t0)
    /* 9DA4 800091A4 2401FFFF */  addiu      $at, $zero, -0x1
    /* 9DA8 800091A8 01015026 */  xor        $t2, $t0, $at
    /* 9DAC 800091AC 3C01FFFF */  lui        $at, (0xFFFF00FF >> 16)
    /* 9DB0 800091B0 314AFF00 */  andi       $t2, $t2, 0xFF00
    /* 9DB4 800091B4 342100FF */  ori        $at, $at, (0xFFFF00FF & 0xFFFF)
    /* 9DB8 800091B8 012A6025 */  or         $t4, $t1, $t2
    /* 9DBC 800091BC 03615824 */  and        $t3, $k1, $at
    /* 9DC0 800091C0 3108FF00 */  andi       $t0, $t0, 0xFF00
    /* 9DC4 800091C4 016C5825 */  or         $t3, $t3, $t4
    /* 9DC8 800091C8 01284824 */  and        $t1, $t1, $t0
    /* 9DCC 800091CC 0361D824 */  and        $k1, $k1, $at
    /* 9DD0 800091D0 AF4B0118 */  sw         $t3, 0x118($k0) /* handwritten instruction */
    /* 9DD4 800091D4 0369D825 */  or         $k1, $k1, $t1
  .Ldk64_boot_800091D8:
    /* 9DD8 800091D8 3C09A430 */  lui        $t1, %hi(D_A430000C)
    /* 9DDC 800091DC 8D29000C */  lw         $t1, %lo(D_A430000C)($t1)
    /* 9DE0 800091E0 1120000B */  beqz       $t1, .Ldk64_boot_80009210
    /* 9DE4 800091E4 00000000 */   nop
    /* 9DE8 800091E8 3C088001 */  lui        $t0, %hi(__OSGlobalIntMask)
    /* 9DEC 800091EC 250800B0 */  addiu      $t0, $t0, %lo(__OSGlobalIntMask)
    /* 9DF0 800091F0 8D080000 */  lw         $t0, 0x0($t0)
    /* 9DF4 800091F4 8F4C0128 */  lw         $t4, 0x128($k0) /* handwritten instruction */
    /* 9DF8 800091F8 2401FFFF */  addiu      $at, $zero, -0x1
    /* 9DFC 800091FC 00084402 */  srl        $t0, $t0, 16
    /* 9E00 80009200 01014026 */  xor        $t0, $t0, $at
    /* 9E04 80009204 3108003F */  andi       $t0, $t0, 0x3F
    /* 9E08 80009208 010C4024 */  and        $t0, $t0, $t4
    /* 9E0C 8000920C 01284825 */  or         $t1, $t1, $t0
  .Ldk64_boot_80009210:
    /* 9E10 80009210 AF490128 */  sw         $t1, 0x128($k0) /* handwritten instruction */
    /* 9E14 80009214 40087000 */  mfc0       $t0, $14 /* handwritten instruction */
    /* 9E18 80009218 AF48011C */  sw         $t0, 0x11C($k0) /* handwritten instruction */
    /* 9E1C 8000921C 8F480018 */  lw         $t0, 0x18($k0) /* handwritten instruction */
    /* 9E20 80009220 11000014 */  beqz       $t0, .Ldk64_boot_80009274
    /* 9E24 80009224 00000000 */   nop
    /* 9E28 80009228 4448F800 */  cfc1       $t0, $31
    /* 9E2C 8000922C 00000000 */  nop
    /* 9E30 80009230 AF48012C */  sw         $t0, 0x12C($k0) /* handwritten instruction */
    /* 9E34 80009234 F7400130 */  sdc1       $f0, 0x130($k0)
    /* 9E38 80009238 F7420138 */  sdc1       $f2, 0x138($k0)
    /* 9E3C 8000923C F7440140 */  sdc1       $f4, 0x140($k0)
    /* 9E40 80009240 F7460148 */  sdc1       $f6, 0x148($k0)
    /* 9E44 80009244 F7480150 */  sdc1       $f8, 0x150($k0)
    /* 9E48 80009248 F74A0158 */  sdc1       $f10, 0x158($k0)
    /* 9E4C 8000924C F74C0160 */  sdc1       $f12, 0x160($k0)
    /* 9E50 80009250 F74E0168 */  sdc1       $f14, 0x168($k0)
    /* 9E54 80009254 F7500170 */  sdc1       $f16, 0x170($k0)
    /* 9E58 80009258 F7520178 */  sdc1       $f18, 0x178($k0)
    /* 9E5C 8000925C F7540180 */  sdc1       $f20, 0x180($k0)
    /* 9E60 80009260 F7560188 */  sdc1       $f22, 0x188($k0)
    /* 9E64 80009264 F7580190 */  sdc1       $f24, 0x190($k0)
    /* 9E68 80009268 F75A0198 */  sdc1       $f26, 0x198($k0)
    /* 9E6C 8000926C F75C01A0 */  sdc1       $f28, 0x1A0($k0)
    /* 9E70 80009270 F75E01A8 */  sdc1       $f30, 0x1A8($k0)
  .Ldk64_boot_80009274:
    /* 9E74 80009274 40086800 */  mfc0       $t0, $13 /* handwritten instruction */
    /* 9E78 80009278 AF480120 */  sw         $t0, 0x120($k0) /* handwritten instruction */
    /* 9E7C 8000927C 24090002 */  addiu      $t1, $zero, 0x2
    /* 9E80 80009280 A7490010 */  sh         $t1, 0x10($k0) /* handwritten instruction */
    /* 9E84 80009284 3109007C */  andi       $t1, $t0, 0x7C
    /* 9E88 80009288 240A0024 */  addiu      $t2, $zero, 0x24
    /* 9E8C 8000928C 112A00AC */  beq        $t1, $t2, .Ldk64_boot_80009540
    /* 9E90 80009290 00000000 */   nop
    /* 9E94 80009294 240A002C */  addiu      $t2, $zero, 0x2C
    /* 9E98 80009298 112A00FB */  beq        $t1, $t2, .Ldk64_boot_80009688
    /* 9E9C 8000929C 00000000 */   nop
    /* 9EA0 800092A0 240A0000 */  addiu      $t2, $zero, 0x0
    /* 9EA4 800092A4 152A00BF */  bne        $t1, $t2, .Ldk64_boot_800095A4
    /* 9EA8 800092A8 00000000 */   nop
    /* 9EAC 800092AC 03688024 */  and        $s0, $k1, $t0
  .Ldk64_boot_800092B0:
    /* 9EB0 800092B0 3209FF00 */  andi       $t1, $s0, 0xFF00
    /* 9EB4 800092B4 00095302 */  srl        $t2, $t1, 12
    /* 9EB8 800092B8 15400003 */  bnez       $t2, .Ldk64_boot_800092C8
    /* 9EBC 800092BC 00000000 */   nop
    /* 9EC0 800092C0 00095202 */  srl        $t2, $t1, 8
    /* 9EC4 800092C4 214A0010 */  addi       $t2, $t2, 0x10 /* handwritten instruction */
  .Ldk64_boot_800092C8:
    /* 9EC8 800092C8 3C018001 */  lui        $at, %hi(D_dk64_boot_80010580)
    /* 9ECC 800092CC 002A0821 */  addu       $at, $at, $t2
    /* 9ED0 800092D0 902A0580 */  lbu        $t2, %lo(D_dk64_boot_80010580)($at)
    /* 9ED4 800092D4 3C018001 */  lui        $at, %hi(jtbl_dk64_boot_800105A0)
    /* 9ED8 800092D8 002A0821 */  addu       $at, $at, $t2
    /* 9EDC 800092DC 8C2A05A0 */  lw         $t2, %lo(jtbl_dk64_boot_800105A0)($at)
    /* 9EE0 800092E0 01400008 */  jr         $t2
    /* 9EE4 800092E4 00000000 */   nop
  jlabel .Ldk64_boot_800092E8
    /* 9EE8 800092E8 2401DFFF */  addiu      $at, $zero, -0x2001
    /* 9EEC 800092EC 1000FFF0 */  b          .Ldk64_boot_800092B0
    /* 9EF0 800092F0 02018024 */   and       $s0, $s0, $at
  jlabel .Ldk64_boot_800092F4
    /* 9EF4 800092F4 2401BFFF */  addiu      $at, $zero, -0x4001
    /* 9EF8 800092F8 1000FFED */  b          .Ldk64_boot_800092B0
    /* 9EFC 800092FC 02018024 */   and       $s0, $s0, $at
  jlabel .Ldk64_boot_80009300
    /* 9F00 80009300 40095800 */  mfc0       $t1, $11 /* handwritten instruction */
    /* 9F04 80009304 40895800 */  mtc0       $t1, $11 /* handwritten instruction */
    /* 9F08 80009308 0C002575 */  jal        send_mesg
    /* 9F0C 8000930C 24040018 */   addiu     $a0, $zero, 0x18
    /* 9F10 80009310 3C01FFFF */  lui        $at, (0xFFFF7FFF >> 16)
    /* 9F14 80009314 34217FFF */  ori        $at, $at, (0xFFFF7FFF & 0xFFFF)
    /* 9F18 80009318 1000FFE5 */  b          .Ldk64_boot_800092B0
    /* 9F1C 8000931C 02018024 */   and       $s0, $s0, $at
  jlabel .Ldk64_boot_80009320
    /* 9F20 80009320 3C098001 */  lui        $t1, %hi(D_dk64_boot_80010100)
    /* 9F24 80009324 25290100 */  addiu      $t1, $t1, %lo(D_dk64_boot_80010100)
    /* 9F28 80009328 8D2A0008 */  lw         $t2, 0x8($t1)
    /* 9F2C 8000932C 2401F7FF */  addiu      $at, $zero, -0x801
    /* 9F30 80009330 02018024 */  and        $s0, $s0, $at
    /* 9F34 80009334 11400007 */  beqz       $t2, .Ldk64_boot_80009354
    /* 9F38 80009338 21290008 */   addi      $t1, $t1, 0x8 /* handwritten instruction */
    /* 9F3C 8000933C 0140F809 */  jalr       $t2
    /* 9F40 80009340 8D3D0004 */   lw        $sp, 0x4($t1)
    /* 9F44 80009344 10400003 */  beqz       $v0, .Ldk64_boot_80009354
    /* 9F48 80009348 24040010 */   addiu     $a0, $zero, 0x10
    /* 9F4C 8000934C 10000082 */  b          .Ldk64_boot_80009558
    /* 9F50 80009350 00000000 */   nop
  .Ldk64_boot_80009354:
    /* 9F54 80009354 0C002575 */  jal        send_mesg
    /* 9F58 80009358 00000000 */   nop
    /* 9F5C 8000935C 1000FFD4 */  b          .Ldk64_boot_800092B0
    /* 9F60 80009360 00000000 */   nop
  jlabel .Ldk64_boot_80009364
    /* 9F64 80009364 3C088001 */  lui        $t0, %hi(__OSGlobalIntMask)
    /* 9F68 80009368 250800B0 */  addiu      $t0, $t0, %lo(__OSGlobalIntMask)
    /* 9F6C 8000936C 8D080000 */  lw         $t0, 0x0($t0)
    /* 9F70 80009370 3C11A430 */  lui        $s1, %hi(D_A4300008)
    /* 9F74 80009374 8E310008 */  lw         $s1, %lo(D_A4300008)($s1)
    /* 9F78 80009378 00084402 */  srl        $t0, $t0, 16
    /* 9F7C 8000937C 02288824 */  and        $s1, $s1, $t0
    /* 9F80 80009380 32290001 */  andi       $t1, $s1, 0x1
    /* 9F84 80009384 11200013 */  beqz       $t1, .Ldk64_boot_800093D4
    /* 9F88 80009388 00000000 */   nop
    /* 9F8C 8000938C 3C0CA404 */  lui        $t4, %hi(D_A4040010)
    /* 9F90 80009390 8D8C0010 */  lw         $t4, %lo(D_A4040010)($t4)
    /* 9F94 80009394 34098008 */  ori        $t1, $zero, 0x8008
    /* 9F98 80009398 3C01A404 */  lui        $at, %hi(D_A4040010)
    /* 9F9C 8000939C 318C0300 */  andi       $t4, $t4, 0x300
    /* 9FA0 800093A0 3231003E */  andi       $s1, $s1, 0x3E
    /* 9FA4 800093A4 11800007 */  beqz       $t4, .Ldk64_boot_800093C4
    /* 9FA8 800093A8 AC290010 */   sw        $t1, %lo(D_A4040010)($at)
    /* 9FAC 800093AC 0C002575 */  jal        send_mesg
    /* 9FB0 800093B0 24040020 */   addiu     $a0, $zero, 0x20
    /* 9FB4 800093B4 12200038 */  beqz       $s1, .Ldk64_boot_80009498
    /* 9FB8 800093B8 00000000 */   nop
    /* 9FBC 800093BC 10000005 */  b          .Ldk64_boot_800093D4
    /* 9FC0 800093C0 00000000 */   nop
  .Ldk64_boot_800093C4:
    /* 9FC4 800093C4 0C002575 */  jal        send_mesg
    /* 9FC8 800093C8 24040058 */   addiu     $a0, $zero, 0x58
    /* 9FCC 800093CC 12200032 */  beqz       $s1, .Ldk64_boot_80009498
    /* 9FD0 800093D0 00000000 */   nop
  .Ldk64_boot_800093D4:
    /* 9FD4 800093D4 32290008 */  andi       $t1, $s1, 0x8
    /* 9FD8 800093D8 11200007 */  beqz       $t1, .Ldk64_boot_800093F8
    /* 9FDC 800093DC 3C01A440 */   lui       $at, %hi(D_A4400010)
    /* 9FE0 800093E0 32310037 */  andi       $s1, $s1, 0x37
    /* 9FE4 800093E4 AC200010 */  sw         $zero, %lo(D_A4400010)($at)
    /* 9FE8 800093E8 0C002575 */  jal        send_mesg
    /* 9FEC 800093EC 24040038 */   addiu     $a0, $zero, 0x38
    /* 9FF0 800093F0 12200029 */  beqz       $s1, .Ldk64_boot_80009498
    /* 9FF4 800093F4 00000000 */   nop
  .Ldk64_boot_800093F8:
    /* 9FF8 800093F8 32290004 */  andi       $t1, $s1, 0x4
    /* 9FFC 800093FC 11200009 */  beqz       $t1, .Ldk64_boot_80009424
    /* A000 80009400 00000000 */   nop
    /* A004 80009404 24090001 */  addiu      $t1, $zero, 0x1
    /* A008 80009408 3C01A450 */  lui        $at, %hi(D_A450000C)
    /* A00C 8000940C 3231003B */  andi       $s1, $s1, 0x3B
    /* A010 80009410 AC29000C */  sw         $t1, %lo(D_A450000C)($at)
    /* A014 80009414 0C002575 */  jal        send_mesg
    /* A018 80009418 24040030 */   addiu     $a0, $zero, 0x30
    /* A01C 8000941C 1220001E */  beqz       $s1, .Ldk64_boot_80009498
    /* A020 80009420 00000000 */   nop
  .Ldk64_boot_80009424:
    /* A024 80009424 32290002 */  andi       $t1, $s1, 0x2
    /* A028 80009428 11200007 */  beqz       $t1, .Ldk64_boot_80009448
    /* A02C 8000942C 3C01A480 */   lui       $at, %hi(D_A4800018)
    /* A030 80009430 3231003D */  andi       $s1, $s1, 0x3D
    /* A034 80009434 AC200018 */  sw         $zero, %lo(D_A4800018)($at)
    /* A038 80009438 0C002575 */  jal        send_mesg
    /* A03C 8000943C 24040028 */   addiu     $a0, $zero, 0x28
    /* A040 80009440 12200015 */  beqz       $s1, .Ldk64_boot_80009498
    /* A044 80009444 00000000 */   nop
  .Ldk64_boot_80009448:
    /* A048 80009448 32290010 */  andi       $t1, $s1, 0x10
    /* A04C 8000944C 11200009 */  beqz       $t1, .Ldk64_boot_80009474
    /* A050 80009450 00000000 */   nop
    /* A054 80009454 24090002 */  addiu      $t1, $zero, 0x2
    /* A058 80009458 3C01A460 */  lui        $at, %hi(D_A4600010)
    /* A05C 8000945C 3231002F */  andi       $s1, $s1, 0x2F
    /* A060 80009460 AC290010 */  sw         $t1, %lo(D_A4600010)($at)
    /* A064 80009464 0C002575 */  jal        send_mesg
    /* A068 80009468 24040040 */   addiu     $a0, $zero, 0x40
    /* A06C 8000946C 1220000A */  beqz       $s1, .Ldk64_boot_80009498
    /* A070 80009470 00000000 */   nop
  .Ldk64_boot_80009474:
    /* A074 80009474 32290020 */  andi       $t1, $s1, 0x20
    /* A078 80009478 11200007 */  beqz       $t1, .Ldk64_boot_80009498
    /* A07C 8000947C 00000000 */   nop
    /* A080 80009480 24090800 */  addiu      $t1, $zero, 0x800
    /* A084 80009484 3C01A430 */  lui        $at, %hi(D_A4300000)
    /* A088 80009488 3231001F */  andi       $s1, $s1, 0x1F
    /* A08C 8000948C AC290000 */  sw         $t1, %lo(D_A4300000)($at)
    /* A090 80009490 0C002575 */  jal        send_mesg
    /* A094 80009494 24040048 */   addiu     $a0, $zero, 0x48
  .Ldk64_boot_80009498:
    /* A098 80009498 2401FBFF */  addiu      $at, $zero, -0x401
    /* A09C 8000949C 1000FF84 */  b          .Ldk64_boot_800092B0
    /* A0A0 800094A0 02018024 */   and       $s0, $s0, $at
  jlabel .Ldk64_boot_800094A4
    /* A0A4 800094A4 8F5B0118 */  lw         $k1, 0x118($k0) /* handwritten instruction */
    /* A0A8 800094A8 2401EFFF */  addiu      $at, $zero, -0x1001
    /* A0AC 800094AC 3C098001 */  lui        $t1, %hi(__osShutdown)
    /* A0B0 800094B0 0361D824 */  and        $k1, $k1, $at
    /* A0B4 800094B4 AF5B0118 */  sw         $k1, 0x118($k0) /* handwritten instruction */
    /* A0B8 800094B8 252900AC */  addiu      $t1, $t1, %lo(__osShutdown)
    /* A0BC 800094BC 8D2A0000 */  lw         $t2, 0x0($t1)
    /* A0C0 800094C0 11400003 */  beqz       $t2, .Ldk64_boot_800094D0
    /* A0C4 800094C4 2401EFFF */   addiu     $at, $zero, -0x1001
    /* A0C8 800094C8 10000023 */  b          .Ldk64_boot_80009558
    /* A0CC 800094CC 02018024 */   and       $s0, $s0, $at
  .Ldk64_boot_800094D0:
    /* A0D0 800094D0 240A0001 */  addiu      $t2, $zero, 0x1
    /* A0D4 800094D4 AD2A0000 */  sw         $t2, 0x0($t1)
    /* A0D8 800094D8 0C002575 */  jal        send_mesg
    /* A0DC 800094DC 24040070 */   addiu     $a0, $zero, 0x70
    /* A0E0 800094E0 3C0A8001 */  lui        $t2, %hi(__osRunQueue)
    /* A0E4 800094E4 8D4A00E8 */  lw         $t2, %lo(__osRunQueue)($t2)
    /* A0E8 800094E8 2401EFFF */  addiu      $at, $zero, -0x1001
    /* A0EC 800094EC 02018024 */  and        $s0, $s0, $at
    /* A0F0 800094F0 8D5B0118 */  lw         $k1, 0x118($t2) /* handwritten instruction */
    /* A0F4 800094F4 0361D824 */  and        $k1, $k1, $at
    /* A0F8 800094F8 10000017 */  b          .Ldk64_boot_80009558
    /* A0FC 800094FC AD5B0118 */   sw        $k1, 0x118($t2) /* handwritten instruction */
  jlabel .Ldk64_boot_80009500
    /* A100 80009500 2401FDFF */  addiu      $at, $zero, -0x201
    /* A104 80009504 01014024 */  and        $t0, $t0, $at
    /* A108 80009508 40886800 */  mtc0       $t0, $13 /* handwritten instruction */
    /* A10C 8000950C 0C002575 */  jal        send_mesg
    /* A110 80009510 24040008 */   addiu     $a0, $zero, 0x8
    /* A114 80009514 2401FDFF */  addiu      $at, $zero, -0x201
    /* A118 80009518 1000FF65 */  b          .Ldk64_boot_800092B0
    /* A11C 8000951C 02018024 */   and       $s0, $s0, $at
  jlabel .Ldk64_boot_80009520
    /* A120 80009520 2401FEFF */  addiu      $at, $zero, -0x101
    /* A124 80009524 01014024 */  and        $t0, $t0, $at
    /* A128 80009528 40886800 */  mtc0       $t0, $13 /* handwritten instruction */
    /* A12C 8000952C 0C002575 */  jal        send_mesg
    /* A130 80009530 24040000 */   addiu     $a0, $zero, 0x0
    /* A134 80009534 2401FEFF */  addiu      $at, $zero, -0x101
    /* A138 80009538 1000FF5D */  b          .Ldk64_boot_800092B0
    /* A13C 8000953C 02018024 */   and       $s0, $s0, $at
  .Ldk64_boot_80009540:
    /* A140 80009540 24090001 */  addiu      $t1, $zero, 0x1
    /* A144 80009544 A7490012 */  sh         $t1, 0x12($k0) /* handwritten instruction */
    /* A148 80009548 0C002575 */  jal        send_mesg
    /* A14C 8000954C 24040050 */   addiu     $a0, $zero, 0x50
    /* A150 80009550 10000001 */  b          .Ldk64_boot_80009558
    /* A154 80009554 00000000 */   nop
  jlabel .Ldk64_boot_80009558
    /* A158 80009558 3C0A8001 */  lui        $t2, %hi(__osRunQueue)
    /* A15C 8000955C 8D4A00E8 */  lw         $t2, %lo(__osRunQueue)($t2)
    /* A160 80009560 8F490004 */  lw         $t1, 0x4($k0) /* handwritten instruction */
    /* A164 80009564 8D4B0004 */  lw         $t3, 0x4($t2)
    /* A168 80009568 012B082A */  slt        $at, $t1, $t3
    /* A16C 8000956C 10200007 */  beqz       $at, .Ldk64_boot_8000958C
    /* A170 80009570 00000000 */   nop
    /* A174 80009574 3C048001 */  lui        $a0, %hi(__osRunQueue)
    /* A178 80009578 03402825 */  or         $a1, $k0, $zero
    /* A17C 8000957C 0C0025EF */  jal        __osEnqueueThread
    /* A180 80009580 248400E8 */   addiu     $a0, $a0, %lo(__osRunQueue)
    /* A184 80009584 08002605 */  j          __osDispatchThread
    /* A188 80009588 00000000 */   nop
  .Ldk64_boot_8000958C:
    /* A18C 8000958C 3C098001 */  lui        $t1, %hi(__osRunQueue)
    /* A190 80009590 252900E8 */  addiu      $t1, $t1, %lo(__osRunQueue)
    /* A194 80009594 8D2A0000 */  lw         $t2, 0x0($t1)
    /* A198 80009598 AF4A0000 */  sw         $t2, 0x0($k0) /* handwritten instruction */
    /* A19C 8000959C 08002605 */  j          __osDispatchThread
    /* A1A0 800095A0 AD3A0000 */   sw        $k0, 0x0($t1) /* handwritten instruction */
  .Ldk64_boot_800095A4:
    /* A1A4 800095A4 3C018001 */  lui        $at, %hi(__osFaultedThread)
    /* A1A8 800095A8 AC3A00F4 */  sw         $k0, %lo(__osFaultedThread)($at) /* handwritten instruction */
    /* A1AC 800095AC 24090001 */  addiu      $t1, $zero, 0x1
    /* A1B0 800095B0 A7490010 */  sh         $t1, 0x10($k0) /* handwritten instruction */
    /* A1B4 800095B4 24090002 */  addiu      $t1, $zero, 0x2
    /* A1B8 800095B8 A7490012 */  sh         $t1, 0x12($k0) /* handwritten instruction */
    /* A1BC 800095BC 400A4000 */  mfc0       $t2, $8 /* handwritten instruction */
    /* A1C0 800095C0 AF4A0124 */  sw         $t2, 0x124($k0) /* handwritten instruction */
    /* A1C4 800095C4 0C002575 */  jal        send_mesg
    /* A1C8 800095C8 24040060 */   addiu     $a0, $zero, 0x60
    /* A1CC 800095CC 08002605 */  j          __osDispatchThread
    /* A1D0 800095D0 00000000 */   nop
.size __osException, . - __osException

/* Handwritten function */
glabel send_mesg
    /* A1D4 800095D4 3C0A8001 */  lui        $t2, %hi(__osEventStateTab)
    /* A1D8 800095D8 254A3B10 */  addiu      $t2, $t2, %lo(__osEventStateTab)
    /* A1DC 800095DC 01445021 */  addu       $t2, $t2, $a0
    /* A1E0 800095E0 8D490000 */  lw         $t1, 0x0($t2)
    /* A1E4 800095E4 03E09025 */  or         $s2, $ra, $zero
    /* A1E8 800095E8 11200025 */  beqz       $t1, .Ldk64_boot_80009680
    /* A1EC 800095EC 00000000 */   nop
    /* A1F0 800095F0 8D2B0008 */  lw         $t3, 0x8($t1)
    /* A1F4 800095F4 8D2C0010 */  lw         $t4, 0x10($t1)
    /* A1F8 800095F8 016C082A */  slt        $at, $t3, $t4
    /* A1FC 800095FC 10200020 */  beqz       $at, .Ldk64_boot_80009680
    /* A200 80009600 00000000 */   nop
    /* A204 80009604 8D2D000C */  lw         $t5, 0xC($t1)
    /* A208 80009608 01AB6821 */  addu       $t5, $t5, $t3
    /* A20C 8000960C 01AC001A */  div        $zero, $t5, $t4
    /* A210 80009610 15800002 */  bnez       $t4, .Ldk64_boot_8000961C
    /* A214 80009614 00000000 */   nop
    /* A218 80009618 0007000D */  break      7
  .Ldk64_boot_8000961C:
    /* A21C 8000961C 2401FFFF */  addiu      $at, $zero, -0x1
    /* A220 80009620 15810004 */  bne        $t4, $at, .Ldk64_boot_80009634
    /* A224 80009624 3C018000 */   lui       $at, (0x80000000 >> 16)
    /* A228 80009628 15A10002 */  bne        $t5, $at, .Ldk64_boot_80009634
    /* A22C 8000962C 00000000 */   nop
    /* A230 80009630 0006000D */  break      6
  .Ldk64_boot_80009634:
    /* A234 80009634 8D2C0014 */  lw         $t4, 0x14($t1)
    /* A238 80009638 00006810 */  mfhi       $t5
    /* A23C 8000963C 000D6880 */  sll        $t5, $t5, 2
    /* A240 80009640 018D6021 */  addu       $t4, $t4, $t5
    /* A244 80009644 8D4D0004 */  lw         $t5, 0x4($t2)
    /* A248 80009648 256A0001 */  addiu      $t2, $t3, 0x1
    /* A24C 8000964C AD8D0000 */  sw         $t5, 0x0($t4)
    /* A250 80009650 AD2A0008 */  sw         $t2, 0x8($t1)
    /* A254 80009654 8D2A0000 */  lw         $t2, 0x0($t1)
    /* A258 80009658 8D4B0000 */  lw         $t3, 0x0($t2)
    /* A25C 8000965C 11600008 */  beqz       $t3, .Ldk64_boot_80009680
    /* A260 80009660 00000000 */   nop
    /* A264 80009664 0C002601 */  jal        __osPopThread
    /* A268 80009668 01202025 */   or        $a0, $t1, $zero
    /* A26C 8000966C 00405025 */  or         $t2, $v0, $zero
    /* A270 80009670 3C048001 */  lui        $a0, %hi(__osRunQueue)
    /* A274 80009674 01402825 */  or         $a1, $t2, $zero
    /* A278 80009678 0C0025EF */  jal        __osEnqueueThread
    /* A27C 8000967C 248400E8 */   addiu     $a0, $a0, %lo(__osRunQueue)
  .Ldk64_boot_80009680:
    /* A280 80009680 02400008 */  jr         $s2
    /* A284 80009684 00000000 */   nop
  .Ldk64_boot_80009688:
    /* A288 80009688 3C013000 */  lui        $at, (0x30000000 >> 16)
    /* A28C 8000968C 01014824 */  and        $t1, $t0, $at
    /* A290 80009690 00094F02 */  srl        $t1, $t1, 28
    /* A294 80009694 240A0001 */  addiu      $t2, $zero, 0x1
    /* A298 80009698 152AFFC2 */  bne        $t1, $t2, .Ldk64_boot_800095A4
    /* A29C 8000969C 00000000 */   nop
    /* A2A0 800096A0 8F5B0118 */  lw         $k1, 0x118($k0) /* handwritten instruction */
    /* A2A4 800096A4 3C012000 */  lui        $at, (0x20000000 >> 16)
    /* A2A8 800096A8 24090001 */  addiu      $t1, $zero, 0x1
    /* A2AC 800096AC 0361D825 */  or         $k1, $k1, $at
    /* A2B0 800096B0 AF490018 */  sw         $t1, 0x18($k0) /* handwritten instruction */
    /* A2B4 800096B4 1000FFB5 */  b          .Ldk64_boot_8000958C
    /* A2B8 800096B8 AF5B0118 */   sw        $k1, 0x118($k0) /* handwritten instruction */
.size send_mesg, . - send_mesg

/* Handwritten function */
glabel __osEnqueueAndYield
    /* A2BC 800096BC 3C058001 */  lui        $a1, %hi(__osRunningThread)
    /* A2C0 800096C0 8CA500F0 */  lw         $a1, %lo(__osRunningThread)($a1)
    /* A2C4 800096C4 40086000 */  mfc0       $t0, $12 /* handwritten instruction */
    /* A2C8 800096C8 8CBB0018 */  lw         $k1, 0x18($a1) /* handwritten instruction */
    /* A2CC 800096CC 35080002 */  ori        $t0, $t0, 0x2
    /* A2D0 800096D0 ACA80118 */  sw         $t0, 0x118($a1)
    /* A2D4 800096D4 FCB00098 */  sd         $s0, 0x98($a1)
    /* A2D8 800096D8 FCB100A0 */  sd         $s1, 0xA0($a1)
    /* A2DC 800096DC FCB200A8 */  sd         $s2, 0xA8($a1)
    /* A2E0 800096E0 FCB300B0 */  sd         $s3, 0xB0($a1)
    /* A2E4 800096E4 FCB400B8 */  sd         $s4, 0xB8($a1)
    /* A2E8 800096E8 FCB500C0 */  sd         $s5, 0xC0($a1)
    /* A2EC 800096EC FCB600C8 */  sd         $s6, 0xC8($a1)
    /* A2F0 800096F0 FCB700D0 */  sd         $s7, 0xD0($a1)
    /* A2F4 800096F4 FCBC00E8 */  sd         $gp, 0xE8($a1)
    /* A2F8 800096F8 FCBD00F0 */  sd         $sp, 0xF0($a1)
    /* A2FC 800096FC FCBE00F8 */  sd         $fp, 0xF8($a1)
    /* A300 80009700 FCBF0100 */  sd         $ra, 0x100($a1)
    /* A304 80009704 13600009 */  beqz       $k1, .Ldk64_boot_8000972C /* handwritten instruction */
    /* A308 80009708 ACBF011C */   sw        $ra, 0x11C($a1)
    /* A30C 8000970C 445BF800 */  cfc1       $k1, $31
    /* A310 80009710 F4B40180 */  sdc1       $f20, 0x180($a1)
    /* A314 80009714 F4B60188 */  sdc1       $f22, 0x188($a1)
    /* A318 80009718 F4B80190 */  sdc1       $f24, 0x190($a1)
    /* A31C 8000971C F4BA0198 */  sdc1       $f26, 0x198($a1)
    /* A320 80009720 F4BC01A0 */  sdc1       $f28, 0x1A0($a1)
    /* A324 80009724 F4BE01A8 */  sdc1       $f30, 0x1A8($a1)
    /* A328 80009728 ACBB012C */  sw         $k1, 0x12C($a1) /* handwritten instruction */
  .Ldk64_boot_8000972C:
    /* A32C 8000972C 8CBB0118 */  lw         $k1, 0x118($a1) /* handwritten instruction */
    /* A330 80009730 3369FF00 */  andi       $t1, $k1, 0xFF00 /* handwritten instruction */
    /* A334 80009734 1120000D */  beqz       $t1, .Ldk64_boot_8000976C
    /* A338 80009738 00000000 */   nop
    /* A33C 8000973C 3C088001 */  lui        $t0, %hi(__OSGlobalIntMask)
    /* A340 80009740 250800B0 */  addiu      $t0, $t0, %lo(__OSGlobalIntMask)
    /* A344 80009744 8D080000 */  lw         $t0, 0x0($t0)
    /* A348 80009748 2401FFFF */  addiu      $at, $zero, -0x1
    /* A34C 8000974C 01014026 */  xor        $t0, $t0, $at
    /* A350 80009750 3C01FFFF */  lui        $at, (0xFFFF00FF >> 16)
    /* A354 80009754 3108FF00 */  andi       $t0, $t0, 0xFF00
    /* A358 80009758 342100FF */  ori        $at, $at, (0xFFFF00FF & 0xFFFF)
    /* A35C 8000975C 01284825 */  or         $t1, $t1, $t0
    /* A360 80009760 0361D824 */  and        $k1, $k1, $at
    /* A364 80009764 0369D825 */  or         $k1, $k1, $t1
    /* A368 80009768 ACBB0118 */  sw         $k1, 0x118($a1) /* handwritten instruction */
  .Ldk64_boot_8000976C:
    /* A36C 8000976C 3C1BA430 */  lui        $k1, %hi(D_A430000C) /* handwritten instruction */
    /* A370 80009770 8F7B000C */  lw         $k1, %lo(D_A430000C)($k1) /* handwritten instruction */
    /* A374 80009774 1360000B */  beqz       $k1, .Ldk64_boot_800097A4 /* handwritten instruction */
    /* A378 80009778 00000000 */   nop
    /* A37C 8000977C 3C1A8001 */  lui        $k0, %hi(__OSGlobalIntMask) /* handwritten instruction */
    /* A380 80009780 275A00B0 */  addiu      $k0, $k0, %lo(__OSGlobalIntMask) /* handwritten instruction */
    /* A384 80009784 8F5A0000 */  lw         $k0, 0x0($k0) /* handwritten instruction */
    /* A388 80009788 8CA80128 */  lw         $t0, 0x128($a1)
    /* A38C 8000978C 2401FFFF */  addiu      $at, $zero, -0x1
    /* A390 80009790 001AD402 */  srl        $k0, $k0, 16
    /* A394 80009794 0341D026 */  xor        $k0, $k0, $at
    /* A398 80009798 335A003F */  andi       $k0, $k0, 0x3F /* handwritten instruction */
    /* A39C 8000979C 0348D024 */  and        $k0, $k0, $t0
    /* A3A0 800097A0 037AD825 */  or         $k1, $k1, $k0
  .Ldk64_boot_800097A4:
    /* A3A4 800097A4 10800003 */  beqz       $a0, .Ldk64_boot_800097B4
    /* A3A8 800097A8 ACBB0128 */   sw        $k1, 0x128($a1) /* handwritten instruction */
    /* A3AC 800097AC 0C0025EF */  jal        __osEnqueueThread
    /* A3B0 800097B0 00000000 */   nop
  .Ldk64_boot_800097B4:
    /* A3B4 800097B4 08002605 */  j          __osDispatchThread
    /* A3B8 800097B8 00000000 */   nop
.size __osEnqueueAndYield, . - __osEnqueueAndYield

glabel __osEnqueueThread
    /* A3BC 800097BC 8C980000 */  lw         $t8, 0x0($a0)
    /* A3C0 800097C0 8CAF0004 */  lw         $t7, 0x4($a1)
    /* A3C4 800097C4 0080C825 */  or         $t9, $a0, $zero
    /* A3C8 800097C8 8F0E0004 */  lw         $t6, 0x4($t8)
    /* A3CC 800097CC 01CF082A */  slt        $at, $t6, $t7
    /* A3D0 800097D0 14200007 */  bnez       $at, .Ldk64_boot_800097F0
    /* A3D4 800097D4 00000000 */   nop
  .Ldk64_boot_800097D8:
    /* A3D8 800097D8 0300C825 */  or         $t9, $t8, $zero
    /* A3DC 800097DC 8F180000 */  lw         $t8, 0x0($t8)
    /* A3E0 800097E0 8F0E0004 */  lw         $t6, 0x4($t8)
    /* A3E4 800097E4 01CF082A */  slt        $at, $t6, $t7
    /* A3E8 800097E8 1020FFFB */  beqz       $at, .Ldk64_boot_800097D8
    /* A3EC 800097EC 00000000 */   nop
  .Ldk64_boot_800097F0:
    /* A3F0 800097F0 8F380000 */  lw         $t8, 0x0($t9)
    /* A3F4 800097F4 ACB80000 */  sw         $t8, 0x0($a1)
    /* A3F8 800097F8 AF250000 */  sw         $a1, 0x0($t9)
    /* A3FC 800097FC 03E00008 */  jr         $ra
    /* A400 80009800 ACA40008 */   sw        $a0, 0x8($a1)
.size __osEnqueueThread, . - __osEnqueueThread

glabel __osPopThread
    /* A404 80009804 8C820000 */  lw         $v0, 0x0($a0)
    /* A408 80009808 8C590000 */  lw         $t9, 0x0($v0)
    /* A40C 8000980C 03E00008 */  jr         $ra
    /* A410 80009810 AC990000 */   sw        $t9, 0x0($a0)
.size __osPopThread, . - __osPopThread

/* Handwritten function */
glabel __osDispatchThread
    /* A414 80009814 3C048001 */  lui        $a0, %hi(__osRunQueue)
    /* A418 80009818 0C002601 */  jal        __osPopThread
    /* A41C 8000981C 248400E8 */   addiu     $a0, $a0, %lo(__osRunQueue)
    /* A420 80009820 3C018001 */  lui        $at, %hi(__osRunningThread)
    /* A424 80009824 AC2200F0 */  sw         $v0, %lo(__osRunningThread)($at)
    /* A428 80009828 24080004 */  addiu      $t0, $zero, 0x4
    /* A42C 8000982C A4480010 */  sh         $t0, 0x10($v0)
    /* A430 80009830 0040D025 */  or         $k0, $v0, $zero
    /* A434 80009834 3C088001 */  lui        $t0, %hi(__OSGlobalIntMask)
    /* A438 80009838 8F5B0118 */  lw         $k1, 0x118($k0) /* handwritten instruction */
    /* A43C 8000983C 250800B0 */  addiu      $t0, $t0, %lo(__OSGlobalIntMask)
    /* A440 80009840 8D080000 */  lw         $t0, 0x0($t0)
    /* A444 80009844 3C01FFFF */  lui        $at, (0xFFFF00FF >> 16)
    /* A448 80009848 3369FF00 */  andi       $t1, $k1, 0xFF00 /* handwritten instruction */
    /* A44C 8000984C 342100FF */  ori        $at, $at, (0xFFFF00FF & 0xFFFF)
    /* A450 80009850 3108FF00 */  andi       $t0, $t0, 0xFF00
    /* A454 80009854 01284824 */  and        $t1, $t1, $t0
    /* A458 80009858 0361D824 */  and        $k1, $k1, $at
    /* A45C 8000985C 0369D825 */  or         $k1, $k1, $t1
    /* A460 80009860 409B6000 */  mtc0       $k1, $12 /* handwritten instruction */
    /* A464 80009864 DF5B0108 */  ld         $k1, 0x108($k0) /* handwritten instruction */
    /* A468 80009868 DF410020 */  ld         $at, 0x20($k0) /* handwritten instruction */
    /* A46C 8000986C DF420028 */  ld         $v0, 0x28($k0) /* handwritten instruction */
    /* A470 80009870 03600013 */  mtlo       $k1
    /* A474 80009874 DF5B0110 */  ld         $k1, 0x110($k0) /* handwritten instruction */
    /* A478 80009878 DF430030 */  ld         $v1, 0x30($k0) /* handwritten instruction */
    /* A47C 8000987C DF440038 */  ld         $a0, 0x38($k0) /* handwritten instruction */
    /* A480 80009880 DF450040 */  ld         $a1, 0x40($k0) /* handwritten instruction */
    /* A484 80009884 DF460048 */  ld         $a2, 0x48($k0) /* handwritten instruction */
    /* A488 80009888 DF470050 */  ld         $a3, 0x50($k0) /* handwritten instruction */
    /* A48C 8000988C DF480058 */  ld         $t0, 0x58($k0) /* handwritten instruction */
    /* A490 80009890 DF490060 */  ld         $t1, 0x60($k0) /* handwritten instruction */
    /* A494 80009894 DF4A0068 */  ld         $t2, 0x68($k0) /* handwritten instruction */
    /* A498 80009898 DF4B0070 */  ld         $t3, 0x70($k0) /* handwritten instruction */
    /* A49C 8000989C DF4C0078 */  ld         $t4, 0x78($k0) /* handwritten instruction */
    /* A4A0 800098A0 DF4D0080 */  ld         $t5, 0x80($k0) /* handwritten instruction */
    /* A4A4 800098A4 DF4E0088 */  ld         $t6, 0x88($k0) /* handwritten instruction */
    /* A4A8 800098A8 DF4F0090 */  ld         $t7, 0x90($k0) /* handwritten instruction */
    /* A4AC 800098AC DF500098 */  ld         $s0, 0x98($k0) /* handwritten instruction */
    /* A4B0 800098B0 DF5100A0 */  ld         $s1, 0xA0($k0) /* handwritten instruction */
    /* A4B4 800098B4 DF5200A8 */  ld         $s2, 0xA8($k0) /* handwritten instruction */
    /* A4B8 800098B8 DF5300B0 */  ld         $s3, 0xB0($k0) /* handwritten instruction */
    /* A4BC 800098BC DF5400B8 */  ld         $s4, 0xB8($k0) /* handwritten instruction */
    /* A4C0 800098C0 DF5500C0 */  ld         $s5, 0xC0($k0) /* handwritten instruction */
    /* A4C4 800098C4 DF5600C8 */  ld         $s6, 0xC8($k0) /* handwritten instruction */
    /* A4C8 800098C8 DF5700D0 */  ld         $s7, 0xD0($k0) /* handwritten instruction */
    /* A4CC 800098CC DF5800D8 */  ld         $t8, 0xD8($k0) /* handwritten instruction */
    /* A4D0 800098D0 DF5900E0 */  ld         $t9, 0xE0($k0) /* handwritten instruction */
    /* A4D4 800098D4 DF5C00E8 */  ld         $gp, 0xE8($k0) /* handwritten instruction */
    /* A4D8 800098D8 03600011 */  mthi       $k1
    /* A4DC 800098DC DF5D00F0 */  ld         $sp, 0xF0($k0) /* handwritten instruction */
    /* A4E0 800098E0 DF5E00F8 */  ld         $fp, 0xF8($k0) /* handwritten instruction */
    /* A4E4 800098E4 DF5F0100 */  ld         $ra, 0x100($k0) /* handwritten instruction */
    /* A4E8 800098E8 8F5B011C */  lw         $k1, 0x11C($k0) /* handwritten instruction */
    /* A4EC 800098EC 409B7000 */  mtc0       $k1, $14 /* handwritten instruction */
    /* A4F0 800098F0 8F5B0018 */  lw         $k1, 0x18($k0) /* handwritten instruction */
    /* A4F4 800098F4 13600013 */  beqz       $k1, .Ldk64_boot_80009944 /* handwritten instruction */
    /* A4F8 800098F8 00000000 */   nop
    /* A4FC 800098FC 8F5B012C */  lw         $k1, 0x12C($k0) /* handwritten instruction */
    /* A500 80009900 44DBF800 */  ctc1       $k1, $31
    /* A504 80009904 D7400130 */  ldc1       $f0, 0x130($k0)
    /* A508 80009908 D7420138 */  ldc1       $f2, 0x138($k0)
    /* A50C 8000990C D7440140 */  ldc1       $f4, 0x140($k0)
    /* A510 80009910 D7460148 */  ldc1       $f6, 0x148($k0)
    /* A514 80009914 D7480150 */  ldc1       $f8, 0x150($k0)
    /* A518 80009918 D74A0158 */  ldc1       $f10, 0x158($k0)
    /* A51C 8000991C D74C0160 */  ldc1       $f12, 0x160($k0)
    /* A520 80009920 D74E0168 */  ldc1       $f14, 0x168($k0)
    /* A524 80009924 D7500170 */  ldc1       $f16, 0x170($k0)
    /* A528 80009928 D7520178 */  ldc1       $f18, 0x178($k0)
    /* A52C 8000992C D7540180 */  ldc1       $f20, 0x180($k0)
    /* A530 80009930 D7560188 */  ldc1       $f22, 0x188($k0)
    /* A534 80009934 D7580190 */  ldc1       $f24, 0x190($k0)
    /* A538 80009938 D75A0198 */  ldc1       $f26, 0x198($k0)
    /* A53C 8000993C D75C01A0 */  ldc1       $f28, 0x1A0($k0)
    /* A540 80009940 D75E01A8 */  ldc1       $f30, 0x1A8($k0)
  .Ldk64_boot_80009944:
    /* A544 80009944 8F5B0128 */  lw         $k1, 0x128($k0) /* handwritten instruction */
    /* A548 80009948 3C1A8001 */  lui        $k0, %hi(__OSGlobalIntMask) /* handwritten instruction */
    /* A54C 8000994C 275A00B0 */  addiu      $k0, $k0, %lo(__OSGlobalIntMask) /* handwritten instruction */
    /* A550 80009950 8F5A0000 */  lw         $k0, 0x0($k0) /* handwritten instruction */
    /* A554 80009954 001AD402 */  srl        $k0, $k0, 16
    /* A558 80009958 037AD824 */  and        $k1, $k1, $k0
    /* A55C 8000995C 001BD840 */  sll        $k1, $k1, 1
    /* A560 80009960 3C1A8001 */  lui        $k0, %hi(__osRcpImTable) /* handwritten instruction */
    /* A564 80009964 275A0670 */  addiu      $k0, $k0, %lo(__osRcpImTable) /* handwritten instruction */
    /* A568 80009968 037AD821 */  addu       $k1, $k1, $k0
    /* A56C 8000996C 977B0000 */  lhu        $k1, 0x0($k1) /* handwritten instruction */
    /* A570 80009970 3C1AA430 */  lui        $k0, %hi(D_A430000C) /* handwritten instruction */
    /* A574 80009974 275A000C */  addiu      $k0, $k0, %lo(D_A430000C) /* handwritten instruction */
    /* A578 80009978 AF5B0000 */  sw         $k1, 0x0($k0) /* handwritten instruction */
    /* A57C 8000997C 00000000 */  nop
    /* A580 80009980 00000000 */  nop
    /* A584 80009984 00000000 */  nop
    /* A588 80009988 00000000 */  nop
    /* A58C 8000998C 42000018 */  eret /* handwritten instruction */
.size __osDispatchThread, . - __osDispatchThread

glabel __osCleanupThread
    /* A590 80009990 0C002F34 */  jal        osDestroyThread
    /* A594 80009994 00002025 */   or        $a0, $zero, $zero
    /* A598 80009998 00000000 */  nop
    /* A59C 8000999C 00000000 */  nop
.size __osCleanupThread, . - __osCleanupThread
