.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.set fp=64

.section .text, "ax"

/* Generated by spimdisasm 1.32.1 */

/* Handwritten function */
glabel osGetCount
    /* AF60 8000A360 40024800 */  mfc0       $v0, $9 /* handwritten instruction */
    /* AF64 8000A364 03E00008 */  jr         $ra
    /* AF68 8000A368 00000000 */   nop
    /* AF6C 8000A36C 00000000 */  nop
.size osGetCount, . - osGetCount
