.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.set fp=64

.section .text, "ax"

/* Generated by spimdisasm 1.32.1 */

glabel __osGetFpcCsr
    /* 6680 80005A80 4442F800 */  cfc1       $v0, $31
    /* 6684 80005A84 03E00008 */  jr         $ra
    /* 6688 80005A88 00000000 */   nop
    /* 668C 80005A8C 00000000 */  nop
.size __osGetFpcCsr, . - __osGetFpcCsr
