.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.set fp=64

.section .text, "ax"

/* Generated by spimdisasm 1.32.1 */

/* Handwritten function */
glabel osInvalDCache
    /* 5120 80004520 18A0001F */  blez       $a1, .Ldk64_boot_800045A0
    /* 5124 80004524 00000000 */   nop
    /* 5128 80004528 240B2000 */  addiu      $t3, $zero, 0x2000
    /* 512C 8000452C 00AB082B */  sltu       $at, $a1, $t3
    /* 5130 80004530 1020001D */  beqz       $at, .Ldk64_boot_800045A8
    /* 5134 80004534 00000000 */   nop
    /* 5138 80004538 00804025 */  or         $t0, $a0, $zero
    /* 513C 8000453C 00854821 */  addu       $t1, $a0, $a1
    /* 5140 80004540 0109082B */  sltu       $at, $t0, $t1
    /* 5144 80004544 10200016 */  beqz       $at, .Ldk64_boot_800045A0
    /* 5148 80004548 00000000 */   nop
    /* 514C 8000454C 310A000F */  andi       $t2, $t0, 0xF
    /* 5150 80004550 11400007 */  beqz       $t2, .Ldk64_boot_80004570
    /* 5154 80004554 2529FFF0 */   addiu     $t1, $t1, -0x10
    /* 5158 80004558 010A4023 */  subu       $t0, $t0, $t2
    /* 515C 8000455C BD150000 */  cache      0x15, 0x0($t0) /* handwritten instruction */
    /* 5160 80004560 0109082B */  sltu       $at, $t0, $t1
    /* 5164 80004564 1020000E */  beqz       $at, .Ldk64_boot_800045A0
    /* 5168 80004568 00000000 */   nop
    /* 516C 8000456C 25080010 */  addiu      $t0, $t0, 0x10
  .Ldk64_boot_80004570:
    /* 5170 80004570 312A000F */  andi       $t2, $t1, 0xF
    /* 5174 80004574 11400006 */  beqz       $t2, .Ldk64_boot_80004590
    /* 5178 80004578 00000000 */   nop
    /* 517C 8000457C 012A4823 */  subu       $t1, $t1, $t2
    /* 5180 80004580 BD350010 */  cache      0x15, 0x10($t1) /* handwritten instruction */
    /* 5184 80004584 0128082B */  sltu       $at, $t1, $t0
    /* 5188 80004588 14200005 */  bnez       $at, .Ldk64_boot_800045A0
    /* 518C 8000458C 00000000 */   nop
  .Ldk64_boot_80004590:
    /* 5190 80004590 BD110000 */  cache      0x11, 0x0($t0) /* handwritten instruction */
    /* 5194 80004594 0109082B */  sltu       $at, $t0, $t1
    /* 5198 80004598 1420FFFD */  bnez       $at, .Ldk64_boot_80004590
    /* 519C 8000459C 25080010 */   addiu     $t0, $t0, 0x10
  .Ldk64_boot_800045A0:
    /* 51A0 800045A0 03E00008 */  jr         $ra
    /* 51A4 800045A4 00000000 */   nop
  .Ldk64_boot_800045A8:
    /* 51A8 800045A8 3C088000 */  lui        $t0, 0x8000
    /* 51AC 800045AC 010B4821 */  addu       $t1, $t0, $t3
    /* 51B0 800045B0 2529FFF0 */  addiu      $t1, $t1, -0x10
  .Ldk64_boot_800045B4:
    /* 51B4 800045B4 BD010000 */  cache      0x01, 0x0($t0) /* handwritten instruction */
    /* 51B8 800045B8 0109082B */  sltu       $at, $t0, $t1
    /* 51BC 800045BC 1420FFFD */  bnez       $at, .Ldk64_boot_800045B4
    /* 51C0 800045C0 25080010 */   addiu     $t0, $t0, (0x80000010 & 0xFFFF)
    /* 51C4 800045C4 03E00008 */  jr         $ra
    /* 51C8 800045C8 00000000 */   nop
    /* 51CC 800045CC 00000000 */  nop
.size osInvalDCache, . - osInvalDCache
