.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.set fp=64

.section .text, "ax"

/* Generated by spimdisasm 1.32.1 */

/* Handwritten function */
glabel osInvalICache
    /* 5E60 80005260 18A00011 */  blez       $a1, .Ldk64_boot_800052A8
    /* 5E64 80005264 00000000 */   nop
    /* 5E68 80005268 240B4000 */  addiu      $t3, $zero, 0x4000
    /* 5E6C 8000526C 00AB082B */  sltu       $at, $a1, $t3
    /* 5E70 80005270 1020000F */  beqz       $at, .Ldk64_boot_800052B0
    /* 5E74 80005274 00000000 */   nop
    /* 5E78 80005278 00804025 */  or         $t0, $a0, $zero
    /* 5E7C 8000527C 00854821 */  addu       $t1, $a0, $a1
    /* 5E80 80005280 0109082B */  sltu       $at, $t0, $t1
    /* 5E84 80005284 10200008 */  beqz       $at, .Ldk64_boot_800052A8
    /* 5E88 80005288 00000000 */   nop
    /* 5E8C 8000528C 310A001F */  andi       $t2, $t0, 0x1F
    /* 5E90 80005290 2529FFE0 */  addiu      $t1, $t1, -0x20
    /* 5E94 80005294 010A4023 */  subu       $t0, $t0, $t2
  .Ldk64_boot_80005298:
    /* 5E98 80005298 BD100000 */  cache      0x10, 0x0($t0) /* handwritten instruction */
    /* 5E9C 8000529C 0109082B */  sltu       $at, $t0, $t1
    /* 5EA0 800052A0 1420FFFD */  bnez       $at, .Ldk64_boot_80005298
    /* 5EA4 800052A4 25080020 */   addiu     $t0, $t0, 0x20
  .Ldk64_boot_800052A8:
    /* 5EA8 800052A8 03E00008 */  jr         $ra
    /* 5EAC 800052AC 00000000 */   nop
  .Ldk64_boot_800052B0:
    /* 5EB0 800052B0 3C088000 */  lui        $t0, 0x8000
    /* 5EB4 800052B4 010B4821 */  addu       $t1, $t0, $t3
    /* 5EB8 800052B8 2529FFE0 */  addiu      $t1, $t1, -0x20
  .Ldk64_boot_800052BC:
    /* 5EBC 800052BC BD000000 */  cache      0x00, 0x0($t0) /* handwritten instruction */
    /* 5EC0 800052C0 0109082B */  sltu       $at, $t0, $t1
    /* 5EC4 800052C4 1420FFFD */  bnez       $at, .Ldk64_boot_800052BC
    /* 5EC8 800052C8 25080020 */   addiu     $t0, $t0, (0x80000020 & 0xFFFF)
    /* 5ECC 800052CC 03E00008 */  jr         $ra
    /* 5ED0 800052D0 00000000 */   nop
    /* 5ED4 800052D4 00000000 */  nop
    /* 5ED8 800052D8 00000000 */  nop
    /* 5EDC 800052DC 00000000 */  nop
.size osInvalICache, . - osInvalICache
