.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.set fp=64

.section .text, "ax"

/* Generated by spimdisasm 1.32.1 */

/* Handwritten function */
glabel osMapTLBRdb
    /* B090 8000A490 40085000 */  mfc0       $t0, $10 /* handwritten instruction */
    /* B094 8000A494 2409001F */  addiu      $t1, $zero, 0x1F
    /* B098 8000A498 40890000 */  mtc0       $t1, $0 /* handwritten instruction */
    /* B09C 8000A49C 40802800 */  mtc0       $zero, $5 /* handwritten instruction */
    /* B0A0 8000A4A0 240A0017 */  addiu      $t2, $zero, 0x17
    /* B0A4 8000A4A4 3C09C000 */  lui        $t1, (0xC0000000 >> 16)
    /* B0A8 8000A4A8 40895000 */  mtc0       $t1, $10 /* handwritten instruction */
    /* B0AC 8000A4AC 3C098000 */  lui        $t1, (0x80000000 >> 16)
    /* B0B0 8000A4B0 00095982 */  srl        $t3, $t1, 6
    /* B0B4 8000A4B4 016A5825 */  or         $t3, $t3, $t2
    /* B0B8 8000A4B8 408B1000 */  mtc0       $t3, $2 /* handwritten instruction */
    /* B0BC 8000A4BC 24090001 */  addiu      $t1, $zero, 0x1
    /* B0C0 8000A4C0 40891800 */  mtc0       $t1, $3 /* handwritten instruction */
    /* B0C4 8000A4C4 00000000 */  nop
    /* B0C8 8000A4C8 42000002 */  tlbwi /* handwritten instruction */
    /* B0CC 8000A4CC 00000000 */  nop
    /* B0D0 8000A4D0 00000000 */  nop
    /* B0D4 8000A4D4 00000000 */  nop
    /* B0D8 8000A4D8 00000000 */  nop
    /* B0DC 8000A4DC 40885000 */  mtc0       $t0, $10 /* handwritten instruction */
    /* B0E0 8000A4E0 03E00008 */  jr         $ra
    /* B0E4 8000A4E4 00000000 */   nop
    /* B0E8 8000A4E8 00000000 */  nop
    /* B0EC 8000A4EC 00000000 */  nop
.size osMapTLBRdb, . - osMapTLBRdb
