.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.set fp=64

.section .text, "ax"

/* Generated by spimdisasm 1.32.1 */

/* Handwritten function */
glabel __osSetCompare
    /* C9E0 8000BDE0 40845800 */  mtc0       $a0, $11 /* handwritten instruction */
    /* C9E4 8000BDE4 03E00008 */  jr         $ra
    /* C9E8 8000BDE8 00000000 */   nop
    /* C9EC 8000BDEC 00000000 */  nop
.size __osSetCompare, . - __osSetCompare
