.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.set fp=64

.section .text, "ax"

/* Generated by spimdisasm 1.32.1 */

glabel __osSetFpcCsr
    /* AF90 8000A390 4442F800 */  cfc1       $v0, $31
    /* AF94 8000A394 44C4F800 */  ctc1       $a0, $31
    /* AF98 8000A398 03E00008 */  jr         $ra
    /* AF9C 8000A39C 00000000 */   nop
.size __osSetFpcCsr, . - __osSetFpcCsr
