.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.set fp=64

.section .text, "ax"

/* Generated by spimdisasm 1.32.1 */

/* Handwritten function */
glabel __osSetSR
    /* AF70 8000A370 40846000 */  mtc0       $a0, $12 /* handwritten instruction */
    /* AF74 8000A374 00000000 */  nop
    /* AF78 8000A378 03E00008 */  jr         $ra
    /* AF7C 8000A37C 00000000 */   nop
.size __osSetSR, . - __osSetSR
