.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.set fp=64

.section .text, "ax"

/* Generated by spimdisasm 1.32.1 */

/* Handwritten function */
glabel osUnmapTLBAll
    /* B040 8000A440 40085000 */  mfc0       $t0, $10 /* handwritten instruction */
    /* B044 8000A444 2409001E */  addiu      $t1, $zero, 0x1E
    /* B048 8000A448 3C0A8000 */  lui        $t2, (0x80000000 >> 16)
    /* B04C 8000A44C 408A5000 */  mtc0       $t2, $10 /* handwritten instruction */
    /* B050 8000A450 40801000 */  mtc0       $zero, $2 /* handwritten instruction */
    /* B054 8000A454 40801800 */  mtc0       $zero, $3 /* handwritten instruction */
  .Ldk64_boot_8000A458:
    /* B058 8000A458 40890000 */  mtc0       $t1, $0 /* handwritten instruction */
    /* B05C 8000A45C 00000000 */  nop
    /* B060 8000A460 42000002 */  tlbwi /* handwritten instruction */
    /* B064 8000A464 00000000 */  nop
    /* B068 8000A468 00000000 */  nop
    /* B06C 8000A46C 2129FFFF */  addi       $t1, $t1, -0x1 /* handwritten instruction */
    /* B070 8000A470 0521FFF9 */  bgez       $t1, .Ldk64_boot_8000A458
    /* B074 8000A474 00000000 */   nop
    /* B078 8000A478 40885000 */  mtc0       $t0, $10 /* handwritten instruction */
    /* B07C 8000A47C 03E00008 */  jr         $ra
    /* B080 8000A480 00000000 */   nop
    /* B084 8000A484 00000000 */  nop
    /* B088 8000A488 00000000 */  nop
    /* B08C 8000A48C 00000000 */  nop
.size osUnmapTLBAll, . - osUnmapTLBAll
