.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.set fp=64

.section .text, "ax"

/* Generated by spimdisasm 1.32.1 */

/* Handwritten function */
glabel osWritebackDCacheAll
    /* 5EE0 800052E0 3C088000 */  lui        $t0, 0x8000
    /* 5EE4 800052E4 240A2000 */  addiu      $t2, $zero, 0x2000
    /* 5EE8 800052E8 010A4821 */  addu       $t1, $t0, $t2
    /* 5EEC 800052EC 2529FFF0 */  addiu      $t1, $t1, -0x10
  .Ldk64_boot_800052F0:
    /* 5EF0 800052F0 BD010000 */  cache      0x01, 0x0($t0) /* handwritten instruction */
    /* 5EF4 800052F4 0109082B */  sltu       $at, $t0, $t1
    /* 5EF8 800052F8 1420FFFD */  bnez       $at, .Ldk64_boot_800052F0
    /* 5EFC 800052FC 25080010 */   addiu     $t0, $t0, (0x80000010 & 0xFFFF)
    /* 5F00 80005300 03E00008 */  jr         $ra
    /* 5F04 80005304 00000000 */   nop
    /* 5F08 80005308 00000000 */  nop
    /* 5F0C 8000530C 00000000 */  nop
.size osWritebackDCacheAll, . - osWritebackDCacheAll
