.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.set fp=64

.section .text, "ax"

/* Generated by spimdisasm 1.32.1 */

/* Handwritten function */
glabel osWritebackDCache
    /* 6270 80005670 18A00011 */  blez       $a1, .Ldk64_boot_800056B8
    /* 6274 80005674 00000000 */   nop
    /* 6278 80005678 240B2000 */  addiu      $t3, $zero, 0x2000
    /* 627C 8000567C 00AB082B */  sltu       $at, $a1, $t3
    /* 6280 80005680 1020000F */  beqz       $at, .Ldk64_boot_800056C0
    /* 6284 80005684 00000000 */   nop
    /* 6288 80005688 00804025 */  or         $t0, $a0, $zero
    /* 628C 8000568C 00854821 */  addu       $t1, $a0, $a1
    /* 6290 80005690 0109082B */  sltu       $at, $t0, $t1
    /* 6294 80005694 10200008 */  beqz       $at, .Ldk64_boot_800056B8
    /* 6298 80005698 00000000 */   nop
    /* 629C 8000569C 310A000F */  andi       $t2, $t0, 0xF
    /* 62A0 800056A0 2529FFF0 */  addiu      $t1, $t1, -0x10
    /* 62A4 800056A4 010A4023 */  subu       $t0, $t0, $t2
  .Ldk64_boot_800056A8:
    /* 62A8 800056A8 BD190000 */  cache      0x19, 0x0($t0) /* handwritten instruction */
    /* 62AC 800056AC 0109082B */  sltu       $at, $t0, $t1
    /* 62B0 800056B0 1420FFFD */  bnez       $at, .Ldk64_boot_800056A8
    /* 62B4 800056B4 25080010 */   addiu     $t0, $t0, 0x10
  .Ldk64_boot_800056B8:
    /* 62B8 800056B8 03E00008 */  jr         $ra
    /* 62BC 800056BC 00000000 */   nop
  .Ldk64_boot_800056C0:
    /* 62C0 800056C0 3C088000 */  lui        $t0, 0x8000
    /* 62C4 800056C4 010B4821 */  addu       $t1, $t0, $t3
    /* 62C8 800056C8 2529FFF0 */  addiu      $t1, $t1, -0x10
  .Ldk64_boot_800056CC:
    /* 62CC 800056CC BD010000 */  cache      0x01, 0x0($t0) /* handwritten instruction */
    /* 62D0 800056D0 0109082B */  sltu       $at, $t0, $t1
    /* 62D4 800056D4 1420FFFD */  bnez       $at, .Ldk64_boot_800056CC
    /* 62D8 800056D8 25080010 */   addiu     $t0, $t0, (0x80000010 & 0xFFFF)
    /* 62DC 800056DC 03E00008 */  jr         $ra
    /* 62E0 800056E0 00000000 */   nop
    /* 62E4 800056E4 00000000 */  nop
    /* 62E8 800056E8 00000000 */  nop
    /* 62EC 800056EC 00000000 */  nop
.size osWritebackDCache, . - osWritebackDCache
