.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.set fp=64

.section .text, "ax"

/* Generated by spimdisasm 1.32.1 */

glabel sqrtf
    /* B860 8000AC60 03E00008 */  jr         $ra
    /* B864 8000AC64 46006004 */   sqrt.s    $f0, $f12
    /* B868 8000AC68 00000000 */  nop
    /* B86C 8000AC6C 00000000 */  nop
.size sqrtf, . - sqrtf
