.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.set fp=64

.section .text, "ax"

/* Generated by spimdisasm 1.32.1 */

/* Handwritten function */
glabel bcopy
    /* C210 8000B610 10C0001A */  beqz       $a2, .Ldk64_boot_8000B67C
    /* C214 8000B614 00A03825 */   or        $a3, $a1, $zero
    /* C218 8000B618 10850018 */  beq        $a0, $a1, .Ldk64_boot_8000B67C
    /* C21C 8000B61C 00A4082A */   slt       $at, $a1, $a0
    /* C220 8000B620 54200008 */  bnel       $at, $zero, .Ldk64_boot_8000B644
    /* C224 8000B624 28C10010 */   slti      $at, $a2, 0x10
    /* C228 8000B628 00861020 */  add        $v0, $a0, $a2 /* handwritten instruction */
    /* C22C 8000B62C 00A2082A */  slt        $at, $a1, $v0
    /* C230 8000B630 50200004 */  beql       $at, $zero, .Ldk64_boot_8000B644
    /* C234 8000B634 28C10010 */   slti      $at, $a2, 0x10
    /* C238 8000B638 1000005B */  b          .Ldk64_boot_8000B7A8
    /* C23C 8000B63C 28C10010 */   slti      $at, $a2, 0x10
    /* C240 8000B640 28C10010 */  slti       $at, $a2, 0x10
  .Ldk64_boot_8000B644:
    /* C244 8000B644 14200005 */  bnez       $at, .Ldk64_boot_8000B65C
    /* C248 8000B648 00000000 */   nop
    /* C24C 8000B64C 30820003 */  andi       $v0, $a0, 0x3
    /* C250 8000B650 30A30003 */  andi       $v1, $a1, 0x3
    /* C254 8000B654 1043000B */  beq        $v0, $v1, .Ldk64_boot_8000B684
    /* C258 8000B658 00000000 */   nop
  .Ldk64_boot_8000B65C:
    /* C25C 8000B65C 10C00007 */  beqz       $a2, .Ldk64_boot_8000B67C
    /* C260 8000B660 00000000 */   nop
    /* C264 8000B664 00861821 */  addu       $v1, $a0, $a2
  .Ldk64_boot_8000B668:
    /* C268 8000B668 80820000 */  lb         $v0, 0x0($a0)
    /* C26C 8000B66C 24840001 */  addiu      $a0, $a0, 0x1
    /* C270 8000B670 24A50001 */  addiu      $a1, $a1, 0x1
    /* C274 8000B674 1483FFFC */  bne        $a0, $v1, .Ldk64_boot_8000B668
    /* C278 8000B678 A0A2FFFF */   sb        $v0, -0x1($a1)
  .Ldk64_boot_8000B67C:
    /* C27C 8000B67C 03E00008 */  jr         $ra
    /* C280 8000B680 00E01025 */   or        $v0, $a3, $zero
  .Ldk64_boot_8000B684:
    /* C284 8000B684 10400018 */  beqz       $v0, .Ldk64_boot_8000B6E8
    /* C288 8000B688 24010001 */   addiu     $at, $zero, 0x1
    /* C28C 8000B68C 1041000F */  beq        $v0, $at, .Ldk64_boot_8000B6CC
    /* C290 8000B690 24010002 */   addiu     $at, $zero, 0x2
    /* C294 8000B694 50410008 */  beql       $v0, $at, .Ldk64_boot_8000B6B8
    /* C298 8000B698 84820000 */   lh        $v0, 0x0($a0)
    /* C29C 8000B69C 80820000 */  lb         $v0, 0x0($a0)
    /* C2A0 8000B6A0 24840001 */  addiu      $a0, $a0, 0x1
    /* C2A4 8000B6A4 24A50001 */  addiu      $a1, $a1, 0x1
    /* C2A8 8000B6A8 24C6FFFF */  addiu      $a2, $a2, -0x1
    /* C2AC 8000B6AC 1000000E */  b          .Ldk64_boot_8000B6E8
    /* C2B0 8000B6B0 A0A2FFFF */   sb        $v0, -0x1($a1)
    /* C2B4 8000B6B4 84820000 */  lh         $v0, 0x0($a0)
  .Ldk64_boot_8000B6B8:
    /* C2B8 8000B6B8 24840002 */  addiu      $a0, $a0, 0x2
    /* C2BC 8000B6BC 24A50002 */  addiu      $a1, $a1, 0x2
    /* C2C0 8000B6C0 24C6FFFE */  addiu      $a2, $a2, -0x2
    /* C2C4 8000B6C4 10000008 */  b          .Ldk64_boot_8000B6E8
    /* C2C8 8000B6C8 A4A2FFFE */   sh        $v0, -0x2($a1)
  .Ldk64_boot_8000B6CC:
    /* C2CC 8000B6CC 80820000 */  lb         $v0, 0x0($a0)
    /* C2D0 8000B6D0 84830001 */  lh         $v1, 0x1($a0)
    /* C2D4 8000B6D4 24840003 */  addiu      $a0, $a0, 0x3
    /* C2D8 8000B6D8 24A50003 */  addiu      $a1, $a1, 0x3
    /* C2DC 8000B6DC 24C6FFFD */  addiu      $a2, $a2, -0x3
    /* C2E0 8000B6E0 A0A2FFFD */  sb         $v0, -0x3($a1)
    /* C2E4 8000B6E4 A4A3FFFE */  sh         $v1, -0x2($a1)
  .Ldk64_boot_8000B6E8:
    /* C2E8 8000B6E8 28C10020 */  slti       $at, $a2, 0x20
    /* C2EC 8000B6EC 54200016 */  bnel       $at, $zero, .Ldk64_boot_8000B748
    /* C2F0 8000B6F0 28C10010 */   slti      $at, $a2, 0x10
    /* C2F4 8000B6F4 8C820000 */  lw         $v0, 0x0($a0)
    /* C2F8 8000B6F8 8C830004 */  lw         $v1, 0x4($a0)
    /* C2FC 8000B6FC 8C880008 */  lw         $t0, 0x8($a0)
    /* C300 8000B700 8C89000C */  lw         $t1, 0xC($a0)
    /* C304 8000B704 8C8A0010 */  lw         $t2, 0x10($a0)
    /* C308 8000B708 8C8B0014 */  lw         $t3, 0x14($a0)
    /* C30C 8000B70C 8C8C0018 */  lw         $t4, 0x18($a0)
    /* C310 8000B710 8C8D001C */  lw         $t5, 0x1C($a0)
    /* C314 8000B714 24840020 */  addiu      $a0, $a0, 0x20
    /* C318 8000B718 24A50020 */  addiu      $a1, $a1, 0x20
    /* C31C 8000B71C 24C6FFE0 */  addiu      $a2, $a2, -0x20
    /* C320 8000B720 ACA2FFE0 */  sw         $v0, -0x20($a1)
    /* C324 8000B724 ACA3FFE4 */  sw         $v1, -0x1C($a1)
    /* C328 8000B728 ACA8FFE8 */  sw         $t0, -0x18($a1)
    /* C32C 8000B72C ACA9FFEC */  sw         $t1, -0x14($a1)
    /* C330 8000B730 ACAAFFF0 */  sw         $t2, -0x10($a1)
    /* C334 8000B734 ACABFFF4 */  sw         $t3, -0xC($a1)
    /* C338 8000B738 ACACFFF8 */  sw         $t4, -0x8($a1)
    /* C33C 8000B73C 1000FFEA */  b          .Ldk64_boot_8000B6E8
    /* C340 8000B740 ACADFFFC */   sw        $t5, -0x4($a1)
  .Ldk64_boot_8000B744:
    /* C344 8000B744 28C10010 */  slti       $at, $a2, 0x10
  .Ldk64_boot_8000B748:
    /* C348 8000B748 5420000E */  bnel       $at, $zero, .Ldk64_boot_8000B784
    /* C34C 8000B74C 28C10004 */   slti      $at, $a2, 0x4
    /* C350 8000B750 8C820000 */  lw         $v0, 0x0($a0)
    /* C354 8000B754 8C830004 */  lw         $v1, 0x4($a0)
    /* C358 8000B758 8C880008 */  lw         $t0, 0x8($a0)
    /* C35C 8000B75C 8C89000C */  lw         $t1, 0xC($a0)
    /* C360 8000B760 24840010 */  addiu      $a0, $a0, 0x10
    /* C364 8000B764 24A50010 */  addiu      $a1, $a1, 0x10
    /* C368 8000B768 24C6FFF0 */  addiu      $a2, $a2, -0x10
    /* C36C 8000B76C ACA2FFF0 */  sw         $v0, -0x10($a1)
    /* C370 8000B770 ACA3FFF4 */  sw         $v1, -0xC($a1)
    /* C374 8000B774 ACA8FFF8 */  sw         $t0, -0x8($a1)
    /* C378 8000B778 1000FFF2 */  b          .Ldk64_boot_8000B744
    /* C37C 8000B77C ACA9FFFC */   sw        $t1, -0x4($a1)
  .Ldk64_boot_8000B780:
    /* C380 8000B780 28C10004 */  slti       $at, $a2, 0x4
  .Ldk64_boot_8000B784:
    /* C384 8000B784 1420FFB5 */  bnez       $at, .Ldk64_boot_8000B65C
    /* C388 8000B788 00000000 */   nop
    /* C38C 8000B78C 8C820000 */  lw         $v0, 0x0($a0)
    /* C390 8000B790 24840004 */  addiu      $a0, $a0, 0x4
    /* C394 8000B794 24A50004 */  addiu      $a1, $a1, 0x4
    /* C398 8000B798 24C6FFFC */  addiu      $a2, $a2, -0x4
    /* C39C 8000B79C 1000FFF8 */  b          .Ldk64_boot_8000B780
    /* C3A0 8000B7A0 ACA2FFFC */   sw        $v0, -0x4($a1)
    /* C3A4 8000B7A4 28C10010 */  slti       $at, $a2, 0x10
  .Ldk64_boot_8000B7A8:
    /* C3A8 8000B7A8 00862020 */  add        $a0, $a0, $a2 /* handwritten instruction */
    /* C3AC 8000B7AC 14200005 */  bnez       $at, .Ldk64_boot_8000B7C4
    /* C3B0 8000B7B0 00A62820 */   add       $a1, $a1, $a2 /* handwritten instruction */
    /* C3B4 8000B7B4 30820003 */  andi       $v0, $a0, 0x3
    /* C3B8 8000B7B8 30A30003 */  andi       $v1, $a1, 0x3
    /* C3BC 8000B7BC 1043000D */  beq        $v0, $v1, .Ldk64_boot_8000B7F4
    /* C3C0 8000B7C0 00000000 */   nop
  .Ldk64_boot_8000B7C4:
    /* C3C4 8000B7C4 10C0FFAD */  beqz       $a2, .Ldk64_boot_8000B67C
    /* C3C8 8000B7C8 00000000 */   nop
    /* C3CC 8000B7CC 2484FFFF */  addiu      $a0, $a0, -0x1
    /* C3D0 8000B7D0 24A5FFFF */  addiu      $a1, $a1, -0x1
    /* C3D4 8000B7D4 00861823 */  subu       $v1, $a0, $a2
  .Ldk64_boot_8000B7D8:
    /* C3D8 8000B7D8 80820000 */  lb         $v0, 0x0($a0)
    /* C3DC 8000B7DC 2484FFFF */  addiu      $a0, $a0, -0x1
    /* C3E0 8000B7E0 24A5FFFF */  addiu      $a1, $a1, -0x1
    /* C3E4 8000B7E4 1483FFFC */  bne        $a0, $v1, .Ldk64_boot_8000B7D8
    /* C3E8 8000B7E8 A0A20001 */   sb        $v0, 0x1($a1)
    /* C3EC 8000B7EC 03E00008 */  jr         $ra
    /* C3F0 8000B7F0 00E01025 */   or        $v0, $a3, $zero
  .Ldk64_boot_8000B7F4:
    /* C3F4 8000B7F4 10400018 */  beqz       $v0, .Ldk64_boot_8000B858
    /* C3F8 8000B7F8 24010003 */   addiu     $at, $zero, 0x3
    /* C3FC 8000B7FC 1041000F */  beq        $v0, $at, .Ldk64_boot_8000B83C
    /* C400 8000B800 24010002 */   addiu     $at, $zero, 0x2
    /* C404 8000B804 50410008 */  beql       $v0, $at, .Ldk64_boot_8000B828
    /* C408 8000B808 8482FFFE */   lh        $v0, -0x2($a0)
    /* C40C 8000B80C 8082FFFF */  lb         $v0, -0x1($a0)
    /* C410 8000B810 2484FFFF */  addiu      $a0, $a0, -0x1
    /* C414 8000B814 24A5FFFF */  addiu      $a1, $a1, -0x1
    /* C418 8000B818 24C6FFFF */  addiu      $a2, $a2, -0x1
    /* C41C 8000B81C 1000000E */  b          .Ldk64_boot_8000B858
    /* C420 8000B820 A0A20000 */   sb        $v0, 0x0($a1)
    /* C424 8000B824 8482FFFE */  lh         $v0, -0x2($a0)
  .Ldk64_boot_8000B828:
    /* C428 8000B828 2484FFFE */  addiu      $a0, $a0, -0x2
    /* C42C 8000B82C 24A5FFFE */  addiu      $a1, $a1, -0x2
    /* C430 8000B830 24C6FFFE */  addiu      $a2, $a2, -0x2
    /* C434 8000B834 10000008 */  b          .Ldk64_boot_8000B858
    /* C438 8000B838 A4A20000 */   sh        $v0, 0x0($a1)
  .Ldk64_boot_8000B83C:
    /* C43C 8000B83C 8082FFFF */  lb         $v0, -0x1($a0)
    /* C440 8000B840 8483FFFD */  lh         $v1, -0x3($a0)
    /* C444 8000B844 2484FFFD */  addiu      $a0, $a0, -0x3
    /* C448 8000B848 24A5FFFD */  addiu      $a1, $a1, -0x3
    /* C44C 8000B84C 24C6FFFD */  addiu      $a2, $a2, -0x3
    /* C450 8000B850 A0A20002 */  sb         $v0, 0x2($a1)
    /* C454 8000B854 A4A30000 */  sh         $v1, 0x0($a1)
  .Ldk64_boot_8000B858:
    /* C458 8000B858 28C10020 */  slti       $at, $a2, 0x20
    /* C45C 8000B85C 54200016 */  bnel       $at, $zero, .Ldk64_boot_8000B8B8
    /* C460 8000B860 28C10010 */   slti      $at, $a2, 0x10
    /* C464 8000B864 8C82FFFC */  lw         $v0, -0x4($a0)
    /* C468 8000B868 8C83FFF8 */  lw         $v1, -0x8($a0)
    /* C46C 8000B86C 8C88FFF4 */  lw         $t0, -0xC($a0)
    /* C470 8000B870 8C89FFF0 */  lw         $t1, -0x10($a0)
    /* C474 8000B874 8C8AFFEC */  lw         $t2, -0x14($a0)
    /* C478 8000B878 8C8BFFE8 */  lw         $t3, -0x18($a0)
    /* C47C 8000B87C 8C8CFFE4 */  lw         $t4, -0x1C($a0)
    /* C480 8000B880 8C8DFFE0 */  lw         $t5, -0x20($a0)
    /* C484 8000B884 2484FFE0 */  addiu      $a0, $a0, -0x20
    /* C488 8000B888 24A5FFE0 */  addiu      $a1, $a1, -0x20
    /* C48C 8000B88C 24C6FFE0 */  addiu      $a2, $a2, -0x20
    /* C490 8000B890 ACA2001C */  sw         $v0, 0x1C($a1)
    /* C494 8000B894 ACA30018 */  sw         $v1, 0x18($a1)
    /* C498 8000B898 ACA80014 */  sw         $t0, 0x14($a1)
    /* C49C 8000B89C ACA90010 */  sw         $t1, 0x10($a1)
    /* C4A0 8000B8A0 ACAA000C */  sw         $t2, 0xC($a1)
    /* C4A4 8000B8A4 ACAB0008 */  sw         $t3, 0x8($a1)
    /* C4A8 8000B8A8 ACAC0004 */  sw         $t4, 0x4($a1)
    /* C4AC 8000B8AC 1000FFEA */  b          .Ldk64_boot_8000B858
    /* C4B0 8000B8B0 ACAD0000 */   sw        $t5, 0x0($a1)
  .Ldk64_boot_8000B8B4:
    /* C4B4 8000B8B4 28C10010 */  slti       $at, $a2, 0x10
  .Ldk64_boot_8000B8B8:
    /* C4B8 8000B8B8 5420000E */  bnel       $at, $zero, .Ldk64_boot_8000B8F4
    /* C4BC 8000B8BC 28C10004 */   slti      $at, $a2, 0x4
    /* C4C0 8000B8C0 8C82FFFC */  lw         $v0, -0x4($a0)
    /* C4C4 8000B8C4 8C83FFF8 */  lw         $v1, -0x8($a0)
    /* C4C8 8000B8C8 8C88FFF4 */  lw         $t0, -0xC($a0)
    /* C4CC 8000B8CC 8C89FFF0 */  lw         $t1, -0x10($a0)
    /* C4D0 8000B8D0 2484FFF0 */  addiu      $a0, $a0, -0x10
    /* C4D4 8000B8D4 24A5FFF0 */  addiu      $a1, $a1, -0x10
    /* C4D8 8000B8D8 24C6FFF0 */  addiu      $a2, $a2, -0x10
    /* C4DC 8000B8DC ACA2000C */  sw         $v0, 0xC($a1)
    /* C4E0 8000B8E0 ACA30008 */  sw         $v1, 0x8($a1)
    /* C4E4 8000B8E4 ACA80004 */  sw         $t0, 0x4($a1)
    /* C4E8 8000B8E8 1000FFF2 */  b          .Ldk64_boot_8000B8B4
    /* C4EC 8000B8EC ACA90000 */   sw        $t1, 0x0($a1)
  .Ldk64_boot_8000B8F0:
    /* C4F0 8000B8F0 28C10004 */  slti       $at, $a2, 0x4
  .Ldk64_boot_8000B8F4:
    /* C4F4 8000B8F4 1420FFB3 */  bnez       $at, .Ldk64_boot_8000B7C4
    /* C4F8 8000B8F8 00000000 */   nop
    /* C4FC 8000B8FC 8C82FFFC */  lw         $v0, -0x4($a0)
    /* C500 8000B900 2484FFFC */  addiu      $a0, $a0, -0x4
    /* C504 8000B904 24A5FFFC */  addiu      $a1, $a1, -0x4
    /* C508 8000B908 24C6FFFC */  addiu      $a2, $a2, -0x4
    /* C50C 8000B90C 1000FFF8 */  b          .Ldk64_boot_8000B8F0
    /* C510 8000B910 ACA20000 */   sw        $v0, 0x0($a1)
    /* C514 8000B914 00000000 */  nop
    /* C518 8000B918 00000000 */  nop
    /* C51C 8000B91C 00000000 */  nop
.size bcopy, . - bcopy
