.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.set fp=64

.section .text, "ax"

/* Generated by spimdisasm 1.32.1 */

/* Handwritten function */
glabel __osDisableInt
    /* 9C20 80009020 40086000 */  mfc0       $t0, $12 /* handwritten instruction */
    /* 9C24 80009024 2401FFFE */  addiu      $at, $zero, -0x2
    /* 9C28 80009028 01014824 */  and        $t1, $t0, $at
    /* 9C2C 8000902C 40896000 */  mtc0       $t1, $12 /* handwritten instruction */
    /* 9C30 80009030 31020001 */  andi       $v0, $t0, 0x1
    /* 9C34 80009034 00000000 */  nop
    /* 9C38 80009038 03E00008 */  jr         $ra
    /* 9C3C 8000903C 00000000 */   nop
.size __osDisableInt, . - __osDisableInt

/* Handwritten function */
glabel __osRestoreInt
    /* 9C40 80009040 40086000 */  mfc0       $t0, $12 /* handwritten instruction */
    /* 9C44 80009044 01044025 */  or         $t0, $t0, $a0
    /* 9C48 80009048 40886000 */  mtc0       $t0, $12 /* handwritten instruction */
    /* 9C4C 8000904C 00000000 */  nop
    /* 9C50 80009050 00000000 */  nop
    /* 9C54 80009054 03E00008 */  jr         $ra
    /* 9C58 80009058 00000000 */   nop
    /* 9C5C 8000905C 00000000 */  nop
.size __osRestoreInt, . - __osRestoreInt
