.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.set fp=64

.section .text, "ax"

/* Generated by spimdisasm 1.32.1 */

/* Handwritten function */
glabel __osProbeTLB
    /* C770 8000BB70 40085000 */  mfc0       $t0, $10 /* handwritten instruction */
    /* C774 8000BB74 310900FF */  andi       $t1, $t0, 0xFF
    /* C778 8000BB78 2401E000 */  addiu      $at, $zero, -0x2000
    /* C77C 8000BB7C 00815024 */  and        $t2, $a0, $at
    /* C780 8000BB80 012A4825 */  or         $t1, $t1, $t2
    /* C784 8000BB84 40895000 */  mtc0       $t1, $10 /* handwritten instruction */
    /* C788 8000BB88 00000000 */  nop
    /* C78C 8000BB8C 00000000 */  nop
    /* C790 8000BB90 00000000 */  nop
    /* C794 8000BB94 42000008 */  tlbp /* handwritten instruction */
    /* C798 8000BB98 00000000 */  nop
    /* C79C 8000BB9C 00000000 */  nop
    /* C7A0 8000BBA0 400B0000 */  mfc0       $t3, $0 /* handwritten instruction */
    /* C7A4 8000BBA4 3C018000 */  lui        $at, (0x80000000 >> 16)
    /* C7A8 8000BBA8 01615824 */  and        $t3, $t3, $at
    /* C7AC 8000BBAC 1560001A */  bnez       $t3, .Ldk64_boot_8000BC18
    /* C7B0 8000BBB0 00000000 */   nop
    /* C7B4 8000BBB4 42000001 */  tlbr /* handwritten instruction */
    /* C7B8 8000BBB8 00000000 */  nop
    /* C7BC 8000BBBC 00000000 */  nop
    /* C7C0 8000BBC0 00000000 */  nop
    /* C7C4 8000BBC4 400B2800 */  mfc0       $t3, $5 /* handwritten instruction */
    /* C7C8 8000BBC8 216B2000 */  addi       $t3, $t3, 0x2000 /* handwritten instruction */
    /* C7CC 8000BBCC 000B5842 */  srl        $t3, $t3, 1
    /* C7D0 8000BBD0 01646024 */  and        $t4, $t3, $a0
    /* C7D4 8000BBD4 15800004 */  bnez       $t4, .Ldk64_boot_8000BBE8
    /* C7D8 8000BBD8 216BFFFF */   addi      $t3, $t3, -0x1 /* handwritten instruction */
    /* C7DC 8000BBDC 40021000 */  mfc0       $v0, $2 /* handwritten instruction */
    /* C7E0 8000BBE0 10000002 */  b          .Ldk64_boot_8000BBEC
    /* C7E4 8000BBE4 00000000 */   nop
  .Ldk64_boot_8000BBE8:
    /* C7E8 8000BBE8 40021800 */  mfc0       $v0, $3 /* handwritten instruction */
  .Ldk64_boot_8000BBEC:
    /* C7EC 8000BBEC 304D0002 */  andi       $t5, $v0, 0x2
    /* C7F0 8000BBF0 11A00009 */  beqz       $t5, .Ldk64_boot_8000BC18
    /* C7F4 8000BBF4 00000000 */   nop
    /* C7F8 8000BBF8 3C013FFF */  lui        $at, (0x3FFFFFC0 >> 16)
    /* C7FC 8000BBFC 3421FFC0 */  ori        $at, $at, (0x3FFFFFC0 & 0xFFFF)
    /* C800 8000BC00 00411024 */  and        $v0, $v0, $at
    /* C804 8000BC04 00021180 */  sll        $v0, $v0, 6
    /* C808 8000BC08 008B6824 */  and        $t5, $a0, $t3
    /* C80C 8000BC0C 004D1020 */  add        $v0, $v0, $t5 /* handwritten instruction */
    /* C810 8000BC10 10000002 */  b          .Ldk64_boot_8000BC1C
    /* C814 8000BC14 00000000 */   nop
  .Ldk64_boot_8000BC18:
    /* C818 8000BC18 2402FFFF */  addiu      $v0, $zero, -0x1
  .Ldk64_boot_8000BC1C:
    /* C81C 8000BC1C 40885000 */  mtc0       $t0, $10 /* handwritten instruction */
    /* C820 8000BC20 03E00008 */  jr         $ra
    /* C824 8000BC24 00000000 */   nop
    /* C828 8000BC28 00000000 */  nop
    /* C82C 8000BC2C 00000000 */  nop
.size __osProbeTLB, . - __osProbeTLB
